### ISSUE TITLE
The plug in page can not load!

### ISSUE THREAD

**Issue by littlee** [gulpjs/gulp#1030]
http://gulpjs.com/plugins/
```
TypeError: Cannot read property 'hits' of undefined
    at formatData (http://gulpjs.com/plugins/js/app.js:1:498)
    at http://gulpjs.com/plugins/js/vendor.js:34:875
    at Array.forEach (native)
    at forEach (http://gulpjs.com/plugins/js/vendor.js:32:1396)
    at transformData (http://gulpjs.com/plugins/js/vendor.js:34:893)
    at transformResponse (http://gulpjs.com/plugins/js/vendor.js:34:2052)
    at deferred.promise.then.wrappedErrback (http://gulpjs.com/plugins/js/vendor.js:34:30662)
    at http://gulpjs.com/plugins/js/vendor.js:35:91
    at Scope.$get.Scope.$eval (http://gulpjs.com/plugins/js/vendor.js:35:8463)
    at Scope.$get.Scope.$digest (http://gulpjs.com/plugins/js/vendor.js:35:6316)
```

**Comment by callumacrae** [comment]
Looks like the registry is having problems again. cc @contra

**Comment by contra** [comment]
gdi... should be back up now. the module we are using to run the registry is extremely unreliable

**Comment by callumacrae** [comment]
Back for me :+1:

**Comment by littlee** [comment]
It works again, thanks.
