### ISSUE TITLE
gulp error module.js:338

### ISSUE THREAD

**Issue by hadiab** [gulpjs/gulp#1040]
when i run gulp in Cmder in my laravel project i got.. this error...
![2015-04-25_14-48-22](https://cloud.githubusercontent.com/assets/8047742/7332784/2c1faf88-eb5a-11e4-840d-3f94953a7112.png)

module.js:338                                                                           
    throw err;                                                                          
          ^                                                                             
Error: Cannot find module 'estraverse'                                                  
    at Function.Module._resolveFilename (module.js:336:15)                              
    at Function.Module._load (module.js:278:25)                                         
    at Module.require (module.js:365:17)                                                
    at require (module.js:384:17)                                                       
    at C:\lamp\www\newjob\node_modules\laravel-elixir\node_modules\browserify\node_modul
es\module-deps\node_modules\detective\node_modules\escodegen\escodegen.js:68:18         
    at Object.<anonymous> (C:\lamp\www\newjob\node_modules\laravel-elixir\node_modules\b
rowserify\node_modules\module-deps\node_modules\detective\node_modules\escodegen\escodeg
en.js:2557:2)                                                                           
    at Module._compile (module.js:460:26)                                               
    at Object.Module._extensions..js (module.js:478:10)                                 
    at Module.load (module.js:355:32)                                                   
    at Function.Module._load (module.js:310:12)

**Comment by tunnckoCore** [comment]
`Cmder` ? What is `Cmder`? Give gulpfile.js to see. Run npm install and etc.

**Comment by hadiab** [comment]
Cmder my command line ..

this is in my gulpfile.js

var elixir = require('laravel-elixir');


elixir(function(mix) {
    mix.sass("app.sass");
});

**Comment by tunnckoCore** [comment]
I cant see `gulp`, read the docs for gulp using.

**Comment by kahwee** [comment]
It's likely the package is not properly installed in `node_modules`. You can try `npm cache clean` and delete your `node_modules` before doing `npm install` once more.

**Comment by contra** [comment]
run `npm install`

**Comment by suryadev-singh** [comment]
I was facing same problem. Because i gave the entry point index.js on commond $ npm init. Give gulpfile.js instead of index.js.
