### ISSUE TITLE
V8flags cache not found

### ISSUE THREAD

**Issue by halleycarleton** [gulpjs/gulp#1047]
I am getting the same error as in [Gulp error on Node 0.12.0 #893](https://github.com/gulpjs/gulp/issues/893) but the solution provided in that issue is not working for me.
```
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/lib/node_modules/gulp/node_modules/v8flags/cache/3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
I uninstalled and reinstalled gulp but the issue persists.

```
$ sudo npm uninstall -g gulp
$ sudo npm install -g gulp
```
I also uninstalled/reinstalled the local module.
```
$ npm uninstall gulp
$ npm install gulp
```

I'm running ubuntu 14.04, node v0.12.2, npm 2.8.4, gulp 3.8.11(global and local, checked with `npm list gulp`/`sudo npm list -g gulp`)

Just upgrade Node from 0.11.x

In `/usr/lib/node_modules/gulp/node_modules/v8flags/cache/` the highest number is `3.26.33.flags.json`

**Comment by halleycarleton** [comment]
Not sure what the issue was, but a complete uninstall and reinstall of node and npm seems to have fixed it.

**Comment by yyankowski** [comment]
npm install gulp -g  
has fixed the issue for me
