### ISSUE TITLE
How to ignore files in gulp.watch?

### ISSUE THREAD

**Issue by twlz0ne** [gulpjs/gulp#1055]
Here is my gulpfile

```js
var files = ['app/assets/js/**/*.js', '!app/assets/js/**/.*js', '!app/assets/js/**/#*js'];

gulp.task('scripts', function () {
  return gulp.src(files)
  .pipe(jshint())
  .pipe(...);
});

gulp.task('watch', function() {
  gulp.watch(files, ['scripts']);
});
``` 

to run the task

```sh
➜ myproj git:(master) ✗ gulp scripts
[14:30:25] Using gulpfile ~/myproj/gulpfile.js
[14:30:25] Starting 'scripts'...
[14:30:25] Finished 'scripts' after 223 ms
```

`watch` failed

```sh
➜ myproj git:(master) ✗ gulp watch
[14:31:36] Using gulpfile ~/myproj/gulpfile.js
[14:31:36] Starting 'watch'...
[14:31:36] 'watch' errored after 14 ms
[14:31:36] Error: ENOENT, no such file or directory '~/myproj/app/assets/js/.#directives.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at Gaze._addToWatched (~/myproj/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:277:14)
    at Gaze.add (~/myproj/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:175:8)
    at new Gaze (~/myproj/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (~/myproj/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (~/myproj/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (~/myproj/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (~/myproj/gulpfile.js:196:8)
    at module.exports (~/myproj/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
```

then i use the gulp-watch

```js
  watch = require('gulp-watch');
  watch(files, function() {
    gulp.run('scripts');
  });
```

work fine, except a warning

```sh
➜ myproj git:(master) ✗ gulp watch
[14:31:46] Using gulpfile ~/myproj/gulpfile.js
[14:31:46] Starting 'watch'...
[14:31:46] Finished 'watch' after 19 ms
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[14:37:22] Starting 'scripts'...
[14:37:23] Finished 'scripts' after 573 ms
```

**Comment by tunnckoCore** [comment]
firstly, `'!app/assets/js/**/#*js'` isn't correct. try `'!app/assets/js/**/.#*js'` or I believe you can pass `dot: true` to  .src method as second argument.
