### ISSUE TITLE
Gulp error have no idea what caused it

### ISSUE THREAD

**Issue by adamchenwei** [gulpjs/gulp#1082]
All I ran is the simple gulpfiles.js like this:
// Include gulp
var gulp = require('gulp');
 // Include plugins
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var rename = require('gulp-rename');
var sass = require('gulp-ruby-sass');
var jshint = require('gulp-jshint');

// Establish tasks to run!
gulp.task('scripts', function() {
    return gulp.src('src/app/**/*.js')
    	//Validate JS (not sure exactly what it does)
    		//.pipe(jshint())
    	// Concatenate JS Files
	      .pipe(concat('main.js'))
	      // .pipe(gulp.dest('build/js'));
	    // Rename and Minify
	    	.pipe(rename({suffix: '.min'}))
        .pipe(uglify())
      // Export Result File
        .pipe(gulp.dest('../pg-prod/js'));
});

gulp.task('sass', function() {
  return sass('src/app/app-styles-collection.scss', {style: 'compressed'})
  		.pipe(concat('styles.css'))
      .pipe(rename({suffix: '.min'}))
      .pipe(gulp.dest('../pg-prod/css'));
});

// Default Task Run
gulp.task('default', ['scripts', 'sass'],function(){
});

And I received error of this, I have no idea how to troubleshoot... pretty new to gulp any help will be really appreciated!

[19:46:10] Using gulpfile ~\gulpfile.js
[19:46:10] Starting 'scripts'...
[19:46:10] Starting 'sass'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new JS_Parse_Error (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:196:18)
    at js_error (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:204:11)
    at croak (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:679:41)
    at token_error (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:683:9)
    at unexpected (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:689:9)
    at expr_atom (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1196:9)
    at maybe_unary (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1358:19)
    at expr_ops (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1393:24)
    at maybe_conditional (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1398:20)
    at maybe_assign (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1422:20)
    at expression (C:\Users\adamchenwei\Documents\googleDrive\www\pg-dev\node_modules\gulp-uglify\node_modules\uglify-js\lib\parse.js:1441:20)

**Comment by tunnckoCore** [comment]
Please format your comment and read [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by popomore** [comment]
Your js can not be parsed by uglify, you can check it.
adamchenwei <notifications@github.com>于2015年5月25日 周一上午10:18写道：
