### ISSUE TITLE
--tasks isn't working in latest 4.0 (aaed69d1)

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#1112]
Command:
```sh
$ npm install gulpjs/gulp#4.0
$ node_modules/.bin/gulp --tasks
```

`gulpfile.js`
```js
var
  gulp = require('gulp');

gulp.task('test', function () {
  console.log('test');
});
```

Expected: A task list.

Actual:
```
[13:58:20] Tasks for /somedir/gulpfile.js

/somedir/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:34
        return gulpInst.get(task).description;
                        ^
TypeError: Object #<Gulp> has no method 'get'
    at /somedir/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:34:25
    at /somedir/node_modules/gulp/node_modules/gulp-cli/lib/shared/log/tasks.js:37:10
    at Array.forEach (native)
    at logTasks (/somedir/node_modules/gulp/node_modules/gulp-cli/lib/shared/log/tasks.js:23:8)
    at /somedir/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js:33:14
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

```sh
# Outputs "test"
$ node_modules/.bin/gulp --tasks-simple
```

```sh
$ node_modules/.bin/gulp test
```

Outputs:

```
[14:06:21] Using gulpfile /somedir/gulpfile.js
[14:06:21] Starting 'test'...
test
```

**Comment by bzitzow** [comment]
+1

**Comment by phated** [comment]
Try it now - should be fixed as of https://github.com/gulpjs/gulp-cli/commit/dc5409639f1eabb70bb943981afba29024268288
