### ISSUE TITLE
Invoking gulp --gulpfile gives error on OSX

### ISSUE THREAD

**Issue by mauron85** [gulpjs/gulp#1129]
Gulp version: 3.9.0
System: OSX 10.10.3

When i invoke:

```gulp --gulpfile dist.gulpfile.js```

I get following error:

```
/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/rechoir/index.js:18
    throw new Error('No module loader found for "'+ext+'".');
          ^
Error: No module loader found for ".gulpfile.js".
    at Object.exports.prepare (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/rechoir/index.js:18:11)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:127:25)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:32)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:91:14
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:38:7
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
```

Version 3.8.0 is ok

**Comment by contra** [comment]
@tkellen looks like the rechoir recognition is faulty when the filename has periods in it

**Comment by phated** [comment]
Known issue https://github.com/tkellen/js-rechoir/issues/24 with fix at https://github.com/tkellen/js-rechoir/pull/26 but it doesn't work fully yet.

**Comment by tkellen** [comment]
Resolved in https://github.com/tkellen/js-rechoir/commit/62fb2a62b6102f9ba07a05c7380ce237bb47b349
