### ISSUE TITLE
No error message on singular glob path

### ISSUE THREAD

**Issue by salarmehr** [gulpjs/gulp#1253]
I'm on version 4 and yet get no notification when there is no corresponding file for a singular glob pattern.

 OS Windows 10
 CLI version 0.4.0
Node.js v0.10.35

**Comment by contra** [comment]
Example repo?

**Comment by callumacrae** [comment]
Confirmed:

```
var gulp = require('gulp');

gulp.task('default', function () {
	return gulp.src('somefile.txt')
		.pipe(gulp.dest('someotherfile.txt'));
});
```

Doesn't throw an error.

**Comment by salarmehr** [comment]
Also, I think it should show some warning where there is no corresponding file for a plural pattern. It's rare that the developer specify a pattern without any corresponding files. A warning had no deleterious effect but can save huge debugging time.

**Comment by vbud** [comment]
I just installed latest gulp 4.0 (both globally and locally) and I get the singular glob error as expected:

```
Error: File not found with singular glob
```

My gulp versions:

```
gulp-testing$ gulp -v
[16:48:03] CLI version 0.4.0
[16:48:03] Local version 4.0.0-alpha.1
```

And [the repo to check it out yourself](https://github.com/vbud/gulp-testing).

**Comment by callumacrae** [comment]
Your repo is working fine for me and throwing the error as expected

**Comment by salarmehr** [comment]
@vbud The repo returns a not clear error: 

~~~~~
D:\lab\gulp\gulp-testing>gulp test
[07:01:12] Using gulpfile D:\lab\gulp\gulp-testing\gulpfile.js
[07:01:12] Starting 'test'...
[07:01:12] 'test' errored after 21 ms
[07:01:12] Error: File not found with singular glob
    at Glob.<anonymous> (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\index.js:34:30)
    at Glob.emit (events.js:95:17)
    at Glob._finish (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:172:8)
    at done (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:652:12)
    at D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:736:12)
    at lstatcb_ (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:728:12)
    at RES (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inflight\inflight.js:23:
    at f (D:\lab\gulp\gulp-testing\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\once\once.js:17:25)
~~~~~

It does not say which file is not found.

**Comment by vbud** [comment]
@salarmehr I agree, these error messages could be much more helpful.

It would be helpful to see the glob string for debugging purposes.

**Comment by salarmehr** [comment]
Oddly, when I copy exactly same file to my current project and run `gulp test` it does not return any error.

~~~~
D:\www\project>gulp test
[07:27:22] Using gulpfile D:\project\gulpfile-.js
[07:27:22] Starting 'test'...
[07:27:22] Finished 'test' after 17 ms

**Comment by vbud** [comment]
Have you done an `npm update` in that project to get the latest state of the gulp 4.0 branch?

**Comment by salarmehr** [comment]
doning `npm update` now I see the `Error: File not found with singular glob
` error.  However it stops gulp in my main project. I don't know which  file is missing ◕︵◕

**Comment by phated** [comment]
@salarmehr There is actually a change for that in https://github.com/gulpjs/glob-stream/commit/7da2da06ee6b10cc941f4167c45216d4358baf15 but it hasn't been versioned and released yet.  I am not sure if we can safely bump a patch version due to some other commits.
