### ISSUE TITLE
Error when trying to install gulp 3 using npm 3.3.4 on Windows

### ISSUE THREAD

**Issue by doberkofler** [gulpjs/gulp#1277]
I have been trying to use npm 3 but when trying to globally install gulp, I get the following error stack:

```
>npm install gulp -g
npm WARN install:inflight ENOENT: no such file or directory, rename 'C:\Program Files\nodejs\node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\nod
e_modules\glob\node_modules\inflight' -> 'C:\Program Files\nodejs\node_modules\gulp\node_modules\inflight'
ansi-regex@2.0.0 node_modules\gulp\node_modules\chalk\node_modules\has-ansi\node_modules\ansi-regex -> node_modules\gulp\node_modules\ansi-regex
ansi-styles@2.1.0 node_modules\gulp\node_modules\chalk\node_modules\ansi-styles -> node_modules\gulp\node_modules\ansi-styles
array-differ@1.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\array-differ -> node_modules\gulp\node_modules\array-differ
array-uniq@1.0.2 node_modules\gulp\node_modules\gulp-util\node_modules\array-uniq -> node_modules\gulp\node_modules\array-uniq
balanced-match@0.2.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-
match -> node_modules\gulp\node_modules\balanced-match
beeper@1.1.0 node_modules\gulp\node_modules\gulp-util\node_modules\beeper -> node_modules\gulp\node_modules\beeper
camelcase@1.2.1 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\camelcase-keys\node_modules\camelcase -> node_mo
dules\gulp\node_modules\camelcase
- ansi-regex@2.0.0 node_modules\gulp\node_modules\chalk\node_modules\strip-ansi\node_modules\ansi-regex
clone@1.0.2 node_modules\gulp\node_modules\gulp-util\node_modules\vinyl\node_modules\clone -> node_modules\gulp\node_modules\clone
clone-stats@0.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\vinyl\node_modules\clone-stats -> node_modules\gulp\node_modules\clone-stats
concat-map@0.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map ->
 node_modules\gulp\node_modules\concat-map
brace-expansion@1.1.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch\node_modules\brace-expansion -> node_modules\gulp\
node_modules\brace-expansion
core-util-is@1.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\core-util-is -> node_modules\gulp\no
de_modules\core-util-is
clone@0.1.19 node_modules\gulp\node_modules\vinyl-fs\node_modules\defaults\node_modules\clone -> node_modules\gulp\node_modules\defaults\node_modules\clone
defaults@1.0.2 node_modules\gulp\node_modules\vinyl-fs\node_modules\defaults -> node_modules\gulp\node_modules\defaults
escape-string-regexp@1.0.3 node_modules\gulp\node_modules\chalk\node_modules\escape-string-regexp -> node_modules\gulp\node_modules\escape-string-regexp
extend@2.0.1 node_modules\gulp\node_modules\liftoff\node_modules\extend -> node_modules\gulp\node_modules\extend
find-index@0.1.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob2base\node_modules\find-index -> node_modules\gulp\node_modul
es\find-index
first-chunk-stream@1.0.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\strip-bom\node_modules\first-chunk-stream -> node_modules\gulp\node_modules\first-
chunk-stream
flagged-respawn@0.3.1 node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn -> node_modules\gulp\node_modules\flagged-respawn
get-stdin@5.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\get-stdin -> node_modules\gulp\node_modules\get-stdin
glob2base@0.0.12 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob2base -> node_modules\gulp\node_modules\glob2base
graceful-fs@1.2.3 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\node_modules\gracef
ul-fs -> node_modules\gulp\node_modules\globule\node_modules\graceful-fs
inherits@1.0.2 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\node_modules\inherits
-> node_modules\gulp\node_modules\globule\node_modules\inherits
graceful-fs@3.0.8 node_modules\gulp\node_modules\vinyl-fs\node_modules\graceful-fs -> node_modules\gulp\node_modules\graceful-fs
- core-util-is@1.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\node_modules\core-util-
is
- inherits@2.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\node_modules\inherits
- isarray@0.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\node_modules\isarray
- string_decoder@0.10.31 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\node_modules\string
_decoder
has-ansi@2.0.0 node_modules\gulp\node_modules\chalk\node_modules\has-ansi -> node_modules\gulp\node_modules\has-ansi
get-stdin@4.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\get-stdin -> node_mod
ules\gulp\node_modules\indent-string\node_modules\get-stdin
inherits@2.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\inherits -> node_modules\gulp\node_modul
es\inherits
is-utf8@0.2.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\strip-bom\node_modules\is-utf8 -> node_modules\gulp\node_modules\is-utf8
isarray@0.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\isarray -> node_modules\gulp\node_modules
\isarray
- wrappy@1.0.1 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\inflight\node_modules\wrappy
- inherits@2.0.1 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\inherits
- balanced-match@0.2.0 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\nod
e_modules\balanced-match
- concat-map@0.0.1 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_mo
dules\concat-map
- brace-expansion@1.1.0 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion
- minimatch@2.0.10 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\minimatch
- wrappy@1.0.1 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\once\node_modules\wrappy
- once@1.3.2 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\once
- glob@4.3.5 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob
- findup-sync@0.2.1 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync
lodash@1.0.2 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\lodash -> node_modules\gulp\n
ode_modules\lodash
lodash._basecopy@3.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash._basecopy -> node_modules\gulp\node_modules\lod
ash._basecopy
lodash._basetostring@3.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash._basetostring -> node_modules\gulp\node_mod
ules\lodash._basetostring
lodash._basevalues@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash._basevalues -> node_modules\gulp\node_modules
\lodash._basevalues
lodash._getnative@3.9.1 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys\node_modules\lodash._getnative -> node_mo
dules\gulp\node_modules\lodash._getnative
lodash._isiterateecall@3.0.9 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash._isiterateecall -> node_modules\gulp\node
_modules\lodash._isiterateecall
lodash._reescape@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash._reescape -> node_modules\gulp\node_modules\lodash._reescape
lodash._reevaluate@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash._reevaluate -> node_modules\gulp\node_modules\lodash._reevaluate
lodash._reinterpolate@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash._reinterpolate -> node_modules\gulp\node_modules\lodash._reinterpolate
lodash.escape@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.escape -> node_modules\gulp\node_modules\lodash.es
cape
lodash.isarguments@3.0.4 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys\node_modules\lodash.isarguments -> node_
modules\gulp\node_modules\lodash.isarguments
lodash.isarray@3.0.4 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys\node_modules\lodash.isarray -> node_modules\
gulp\node_modules\lodash.isarray
lodash.keys@3.1.2 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.keys -> node_modules\gulp\node_modules\lodash.keys
lodash.restparam@3.6.1 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.restparam -> node_modules\gulp\node_modules\lod
ash.restparam
lodash.templatesettings@3.1.0 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template\node_modules\lodash.templatesettings -> node_modules\gulp\no
de_modules\lodash.templatesettings
lodash.template@3.6.2 node_modules\gulp\node_modules\gulp-util\node_modules\lodash.template -> node_modules\gulp\node_modules\lodash.template
lru-cache@2.7.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch\node_modules\lru
-cache -> node_modules\gulp\node_modules\lru-cache
map-obj@1.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\camelcase-keys\node_modules\map-obj -> node_module
s\gulp\node_modules\map-obj
camelcase-keys@1.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\camelcase-keys -> node_modules\gulp\node_mo
dules\camelcase-keys
minimatch@2.0.10 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\minimatch -> node_modules\gulp\node_modules\minimatch
minimist@0.0.8 node_modules\gulp\node_modules\vinyl-fs\node_modules\mkdirp\node_modules\minimist -> node_modules\gulp\node_modules\mkdirp\node_modules\minimist
mkdirp@0.5.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\mkdirp -> node_modules\gulp\node_modules\mkdirp
number-is-nan@1.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_mo
dules\is-finite\node_modules\number-is-nan -> node_modules\gulp\node_modules\number-is-nan
is-finite@1.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating\node_module
s\is-finite -> node_modules\gulp\node_modules\is-finite
object-assign@3.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\object-assign -> node_modules\gulp\node_modules\object-assign
ordered-read-streams@0.1.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\ordered-read-streams -> node_modules\gulp\node_modules\
ordered-read-streams
os-homedir@1.0.1 node_modules\gulp\node_modules\tildify\node_modules\os-homedir -> node_modules\gulp\node_modules\os-homedir
process-nextick-args@1.0.3 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\process-nextick-args -> node
_modules\gulp\node_modules\process-nextick-args
repeating@1.1.3 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string\node_modules\repeating -> node_mod
ules\gulp\node_modules\repeating
indent-string@1.2.2 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\indent-string -> node_modules\gulp\node_modu
les\indent-string
meow@3.3.0 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow -> node_modules\gulp\node_modules\meow
dateformat@1.0.11 node_modules\gulp\node_modules\gulp-util\node_modules\dateformat -> node_modules\gulp\node_modules\dateformat
replace-ext@0.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\replace-ext -> node_modules\gulp\node_modules\replace-ext
resolve@1.1.6 node_modules\gulp\node_modules\liftoff\node_modules\resolve -> node_modules\gulp\node_modules\resolve
rechoir@0.6.2 node_modules\gulp\node_modules\liftoff\node_modules\rechoir -> node_modules\gulp\node_modules\rechoir
sequencify@0.0.7 node_modules\gulp\node_modules\orchestrator\node_modules\sequencify -> node_modules\gulp\node_modules\sequencify
sigmund@1.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch\node_modules\sigmu
nd -> node_modules\gulp\node_modules\sigmund
minimatch@0.2.14 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\minimatch -> node_modules
\gulp\node_modules\globule\node_modules\minimatch
glob@3.1.21 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob -> node_modules\gulp\node
_modules\globule\node_modules\glob
globule@0.1.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule -> node_modules\gulp\node_modules\globule

gaze@0.5.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze -> node_modules\gulp\node_modules\gaze
glob-watcher@0.0.6 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher -> node_modules\gulp\node_modules\glob-watcher
stream-consume@0.1.0 node_modules\gulp\node_modules\orchestrator\node_modules\stream-consume -> node_modules\gulp\node_modules\stream-consume
string_decoder@0.10.31 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder -> node_modules\g
ulp\node_modules\string_decoder
readable-stream@1.1.13 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream -> node_modules\gulp\
node_modules\readable-stream
duplexer2@0.0.2 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2 -> node_modules\gulp\node_modules\duplexer2
multipipe@0.1.2 node_modules\gulp\node_modules\gulp-util\node_modules\multipipe -> node_modules\gulp\node_modules\multipipe
strip-ansi@3.0.0 node_modules\gulp\node_modules\chalk\node_modules\strip-ansi -> node_modules\gulp\node_modules\strip-ansi
strip-bom@1.0.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\strip-bom -> node_modules\gulp\node_modules\strip-bom
supports-color@2.0.0 node_modules\gulp\node_modules\chalk\node_modules\supports-color -> node_modules\gulp\node_modules\supports-color
unique-stream@1.0.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream -> node_modules\gulp\node_modules\unique-stream
user-home@1.1.1 node_modules\gulp\node_modules\v8flags\node_modules\user-home -> node_modules\gulp\node_modules\user-home
util-deprecate@1.0.1 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream\node_modules\util-deprecate -> node_modules\gul
p\node_modules\util-deprecate
readable-stream@2.0.2 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\readable-stream -> node_modules\gulp\node_modules\through2\nod
e_modules\readable-stream
vinyl@0.5.3 node_modules\gulp\node_modules\gulp-util\node_modules\vinyl -> node_modules\gulp\node_modules\vinyl
clone@0.2.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\vinyl\node_modules\clone -> node_modules\gulp\node_modules\vinyl-fs\node_modules\clone
- wrappy@1.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inflight\node_modules\wrappy
- inherits@2.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inherits
- wrappy@1.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\once\node_modules\wrappy
- once@1.3.2 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\once
- inflight@1.0.4 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\node_modules\inflight
readable-stream@1.0.33 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream -> node_modules\gulp\node_modules\vinyl-fs\nod
e_modules\readable-stream
- core-util-is@1.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\node_modules\core-util-is
- inherits@2.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\node_modules\inherits
- isarray@0.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\node_modules\isarray
- string_decoder@0.10.31 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\node_modules\string_decoder
- xtend@4.0.0 node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\xtend
- clone-stats@0.0.1 node_modules\gulp\node_modules\vinyl-fs\node_modules\vinyl\node_modules\clone-stats
wrappy@1.0.1 node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once\node_modules\wrappy -> node_modules\gulp\node_modules\wrap
py
once@1.3.2 node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once -> node_modules\gulp\node_modules\once
end-of-stream@0.1.5 node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream -> node_modules\gulp\node_modules\end-of-stream
inflight@1.0.4 node_modules\gulp\node_modules\liftoff\node_modules\findup-sync\node_modules\glob\node_modules\inflight -> node_modules\gulp\node_modules\infligh
t
glob@4.5.3 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob -> node_modules\gulp\node_modules\glob-stream\node_modules\glob
xtend@4.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\through2\node_modules\xtend -> node_modules\gulp\node_modules\xtend
through2@2.0.0 node_modules\gulp\node_modules\gulp-util\node_modules\through2 -> node_modules\gulp\node_modules\through2
glob-stream@3.1.18 node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream -> node_modules\gulp\node_modules\glob-stream
C:\Program Files\nodejs
└── (empty)

npm ERR! code 1

>gulp --version
module.js:338
    throw err;
    ^

Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\gulp\node_modules\liftoff\lib\file_search.js:1:78)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by contra** [comment]
your install failed, npm is very unreliable. wipe your node_modules and do it again.
