### ISSUE TITLE
Error: gulp-sourcemap-write: Streaming not supported

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp#1286]
I've run `npm install` in my project root folder without changing any dep version in `package.json` and I run into this error when running the browserify task:

```
Error: gulp-sourcemap-write: Streaming not supported
    at DestroyableTransform.sourceMapWrite [as _transform] (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:157:23)
    at DestroyableTransform.Transform._read (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at Duplexify._write (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/duplexify/index.js:200:22)
    at doWrite (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at Writable.write (/Users/ibc/src/projectX/node_modules/gulp/node_modules/vinyl-fs/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:239:11)
```

My versions:

* `gulp-cli` branch 0.4.0 globally installed (updated today via `npm install -g gulpjs/gulp-cli#4.0`).
* `gulp` 4.0.0-alpha.1 locally instaled (updated today with `git+https://github.com/gulpjs/gulp.git#4.0`).

The browserify task looks as follows:

```js
var vinylSourceStream = require('vinyl-source-stream');

var browserify  = require('browserify');
var gulp = require('gulp');
var rename = ('gulp-rename');
const PKG = require('./package.json');

gulp.task('browserify', function()
{
	return browserify([path.join(__dirname, PKG.main)])
		.bundle()
			.pipe(vinylSourceStream(PKG.name + '.js'))
			.pipe(header(banner, bannerOptions))
			.pipe(rename('test.js'))
			.pipe(gulp.dest('./out'));
});
```

If I remove the `.pipe(header(banner, bannerOptions))` it works.

**Comment by contra** [comment]
This is from an update to vinyl-fs. I suggest you pin your install of gulp to a specific commit if you are loading off github or regressions like this might end up hitting you. Fixing this now.

**Comment by ibc** [comment]
Thanks a lot. Finally I've splitted both the "browserify" and the "header" in two different serial tasks.

**Comment by contra** [comment]
@ibc Published as vinyl-fs 2.1.1 - a `npm update` should fix you right up. LMK if you have any more problems

**Comment by ibc** [comment]
It works
:cake:

**Comment by phated** [comment]
Btw, thanks for testing out the new stuff. It helps us catch these things before we release.

**Comment by ibc** [comment]
It's nothing. In fact I use gulp branch 4.0 in all my libs due the need of `parallel` and `series` :)
