### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/4.5.103.33.flags.json'

### ISSUE THREAD

**Issue by aaron-goshine** [gulpjs/gulp#1291]
gulp version : 3.9.0" &&  node : v4.1.1
----
Error: Cannot find module '/usr/local/lib/node_modules/gulp/node_modules/v8flags/4.5.103.33.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

**Comment by phated** [comment]
You've recently upgraded your node and you didn't uninstall and cleanly install gulp.  Please do a search before opening issues like this.

**Comment by m4nuC** [comment]
Well I did google this error and landed here... So to make this actually useful:

1- `$ npm uninstall -g gulp`
2-  `npm install -g gulp`
