### ISSUE TITLE
fix for #810 "Cannot find module .../v8flags/cache/3.28.73.flags.json"

### ISSUE THREAD

**Issue by brianally** [gulpjs/gulp#1317]
#810 has been locked except for collaborators. If none of the suggested workarounds there helped (and they did not for me) you can try this hack.

First, the preliminaries.This is what I see on *my* system. YMMV.

    $ node -v
    v0.12.0
    $ npm uninstall gulp
    $ npm uninstall -g gulp
    unbuild gulp@3.9.0
    $ npm install --save-dev gulp
    npm WARN package.json temp@1.0.0 No repository field.
    npm WARN package.json temp@1.0.0 No README data
    gulp@3.9.0 node_modules/gulp
    ├── interpret@0.6.6
    ├── pretty-hrtime@1.0.1
    ├── deprecated@0.0.1
    ├── archy@1.0.0
    ├── minimist@1.2.0
    ├── tildify@1.1.2 (os-homedir@1.0.1)
    ├── semver@4.3.6
    ├── v8flags@2.0.10 (user-home@1.1.1)
    ├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
    ├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
    ├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
    └── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

This is what I see when I try running gulp:

    $ gulp build
    module.js:338
        throw err;
              ^
    Error: Cannot find module '/usr/lib/node_modules/gulp/node_modules/v8flags/cache/3.28.73.flags.json'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:25:22)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)

Just for the hell of it ...

    $ sudo cp /usr/lib/node_modules/gulp/node_modules/v8flags/cache/3.2{6.33,8.73}.flags.json
    [sudo] password for bally:
    $ gulp build
    [17:33:05] Using gulpfile ~/dev/temp/gulpfile.js
    [17:33:05] Starting 'build'...
    [17:33:05] Finished 'build' after 17 ms

If you do this you should check which is the latest version on your system and copy that one. For example:

    $ ll /usr/lib/node_modules/gulp/node_modules/v8flags/cache/
    total 204K
    -rw-r--r-- 1 nobody bally 3.6K Dec 22  2014 3.11.10.15.flags.json
    -rw-r--r-- 1 nobody bally 3.6K Dec 22  2014 3.11.10.17.flags.json
    -rw-r--r-- 1 nobody bally 3.6K Dec 22  2014 3.11.10.19.flags.json
    ... bunch of other files ...
    -rw-r--r-- 1 nobody bally 6.6K Dec 22  2014 3.26.33.flags.json

3.26.33 is my latest latest version. Copy that one.

Now you should probably make a note of that copied file somewhere, and consider removing the copied file before updating Gulp the next time. Use at your own risk.

**Comment by phated** [comment]
Most people would solve this by removing gulp and reinstalling.  This problem may also come up if your permissions were messed up.  You should fix one of those 2 things instead of the above hacky workarounds.
