### ISSUE TITLE
Error: watch ENOSPC     at exports._errnoException (util.js:746:11)

### ISSUE THREAD

**Issue by sajjadmurtaza-ror** [gulpjs/gulp#1335]
➜  test-project git:(master) ✗ gulp serve                  
   [17:58:12] Using gulpfile ~/test-project/gulpfile.js
   [17:58:12] Starting 'styles'...
   [17:58:12] Starting 'elements'...
   [17:58:12] Starting 'images'...
   [17:58:12] Finished 'elements' after 286 ms
   [17:58:12] styles all files 98 B
   [17:58:12] Finished 'styles' after 682 ms
   [17:58:12] images all files 35.41 kB
   [17:58:12] Finished 'images' after 352 ms
   [17:58:12] Starting 'serve'...
   [17:58:12] 'serve' errored after 52 ms
   [17:58:12] Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)

![screenshot from 2015-10-19 18 01 06](https://cloud.githubusercontent.com/assets/8552702/10578416/79b8d564-768b-11e5-842a-88e3c1ce869e.png)

**Comment by TrySound** [comment]
@sajjadmurtaza-ror Use [chokidar](https://github.com/paulmillr/chokidar) instead. Gaze is too buggy :)

**Comment by TrySound** [comment]
@sajjadmurtaza-ror Gaze is gulp3 watcher. gulp4 will use chokidar

**Comment by TrySound** [comment]
@sajjadmurtaza-ror However nospc error means, that you don't have a space on your drive.

**Comment by callumacrae** [comment]
https://github.com/gulpjs/gulp/issues/217

**Comment by mksowmya** [comment]
Resetting the memory fixed the problem for me. Thanks
