### ISSUE TITLE
Karma + Gulp4: FormatError

### ISSUE THREAD

**Issue by robertbaker** [gulpjs/gulp#1354]
```
var karmaConfig = {
        configFile: __dirname + '/' + config.karma,
        singleRun: true,
        autoWatch: false
    };

gulp.task('test', gulp.series('compile:build', function testing(done) {
    var karma = new plugins.karma.Server(karmaConfig, done);
    karma.start();
}));

```

```
[14:52:25] Error: 1
    at formatError (C:\Program Files\nodejs\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.1\formatError.js:20:10)
    at Gulp.<anonymous> (C:\Program Files\nodejs\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.1\log\events.js:26:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Object.error (c:\git\pos\node_modules\undertaker\lib\helpers\createExtensions.js:58:10)
    at handler (c:\git\pos\node_modules\now-and-later\lib\map.js:46:14)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at done (c:\git\pos\node_modules\async-done\index.js:24:15)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at handler (c:\git\pos\node_modules\now-and-later\lib\mapSeries.js:44:16)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at f (c:\git\pos\node_modules\once\once.js:17:25)
    at done (c:\git\pos\node_modules\async-done\index.js:24:15)
    at removeAllListeners (c:\git\pos\node_modules\karma\lib\server.js:332:7)
    at Server.<anonymous> (c:\git\pos\node_modules\karma\lib\server.js:343:9)
```

**Comment by phated** [comment]
I have no idea what you are even doing here.  This issue tracker isn't the place to open issues related to external modules you are bringing in.  If you can actually write up what the issue is, we can better guide you.

**Comment by robertbaker** [comment]
It's a gulp 4 format error. It happens when using karma and `done`. Using the `done` callback throws the format error. It's something with gulp4 not liking how karma exits.

I seen similar issues related to gulp 4 and mentioning of gulp4 error handling and reporting needs to be improved.

If it's karma that needs updated to handle gulp4 error handling, then I will post an issue there. But signs point to this being a gulp4 issue.

Sometimes I also get a 'Did you forget to call async?' message.

**Comment by phated** [comment]
@robertbaker if you are getting the async message you aren't using gulp 4 correctly.  I can't tell anything from your stack trace and it looks like you are getting a non-error object passed as the 1st argument to a callback function.  If you aren't able to find the root cause of this issue in karma then we don't have anything to do here.
