### ISSUE TITLE
Can't load babel/register with new Babel 6

### ISSUE THREAD

**Issue by schovi** [gulpjs/gulp#1359]
I tried to update my project to babel 6 and gulp stopped working.

I have gulp 3.9.0 and when i try to run it throws error on requiring babel/register

```
[00:00:19] Failed to load external module babel-core/register
[00:00:19] Failed to load external module babel/register

(function (exports, require, module, __filename, __dirname) { import ...
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
```

when i try to run require from node repl it fails with following.

```
> require('babel/register')
Error: Cannot find module './lib/api/register/node-polyfill'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/schovi/work/webpack-chrome-extension/node_modules/babel-core/register.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

My guess is that something terrible has changed with new babel, but cant find what  :)

**Comment by phated** [comment]
This is a problem with babel. Please open it there.

**Comment by robbie-c** [comment]
This was top of a search, so although this is the wrong place for it, here is the answer:

It now needs to be

    require('babel-core/register');

See https://babeljs.io/docs/usage/require/

Additionally, babel no longer transpiles by default, so you might need a `.babelrc` like:

    {
      "presets": [
        "es2015",
        "react"
      ]
    }
