### ISSUE TITLE
gulpfile.babel.js stops working with babel-core 6.0.2

### ISSUE THREAD

**Issue by juergenzimmermann** [gulpjs/gulp#1360]
After upgrading babel from 5.8.x to 6.0.2 I'm getting this stacktrace:
```
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (c:\temp\buch\node_modules\babel-core\lib\api\register\node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (c:\temp\buch\node_modules\babel-core\lib\api\register\node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (C:\Zimmermann\npm-config\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Zimmermann\npm-config\node_modules\gulp\node_modules\liftoff\index.js:192:16)
```

**Comment by phated** [comment]
Babel problem, not gulp

**Comment by cx-emerge** [comment]
https://github.com/gulpjs/gulp/issues/1364
