### ISSUE TITLE
Support for Babel Core ^6.0.0

### ISSUE THREAD

**Issue by rish** [gulpjs/gulp#1364]
So creating a new `gulpfile.babel.js` using the most recent version of Babel core (6.0.14)

```
// gulpfile.babel.js
import gulp from 'gulp';

gulp.task('default', () =>
  console.log('howdy')
);
```

I get this error:

```
[00:13:37] Requiring external module babel-core/register
/Users/me/dev/wtf/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at loader (/Users/me/dev/wtf/node_modules/babel-core/lib/api/register/node.js:136:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/me/dev/wtf/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/Users/me/.nodenv/versions/5.0.0/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/me/.nodenv/versions/5.0.0/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
```

Where as using `5.8.33` output works fine:

```
[00:13:37] Requiring external module babel-core/register
[00:13:37] Using gulpfile ~/dev/wtf/gulpfile.babel.js
[00:13:37] Starting 'default'...
howdy
[00:13:37] Finished 'default' after 112 μs
```

This might be a false alarm for this repo and could be due to the breaking changes of Babel, so creating this issue just in case anyone receives the same problem.

`node -v` gives me `v5.0.0` and works fine with `^5.8.0` of `babel-core`.

Contents of failing `package.json`:

```
{
  "name": "wtf",
  "devDependencies": {
    "babel-core": "^6.0.0",
    "gulp": "^3.9.0"
  }
}
```

**Comment by rish** [comment]
So if you would like to use Babel Core `^6.0.0` then you need to use the present plugin:

`npm install --save-dev babel-preset-es2015`

And create a new `.babelrc` file:

```
{
  "presets": ["es2015"]
}
```

Your `package.json` should now (roughly) look like this:

```
{
  "name": "wtf",
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-preset-es2015": "^6.0.14",
    "gulp": "^3.9.0"
  }
}
```

**Comment by phated** [comment]
The upgrade process as described by @rish seems correct. You can't just be upgrading dependencies to the next major version with checking the breaking changes. Gulp doesn't depend on babel, so this is completely the responsibility of the consumer.

**Comment by joseluisq** [comment]
> So if you would like to use Babel Core ^6.0.0 then you need to use the present plugin:
> 
> npm install --save-dev babel-preset-es2015
> 
> And create a new .babelrc file:
> 
> {
>   "presets": ["es2015"]
> }
> Your package.json should now (roughly) look like this:
> 
> {
>   "name": "wtf",
>   "devDependencies": {
>     "babel-core": "^6.0.0",
>     "babel-preset-es2015": "^6.0.14",
>     "gulp": "^3.9.0"
>   }
> }

@rish Using `babel-preset-es2015` plugin and `.babelrc` gulp works fine with ES6.
:+1:

**Comment by jdat82** [comment]
Indeed it works but it is so much slower now. There is a clear latency between the moment I launch gulp and the moment it begins to work.

**Comment by callumacrae** [comment]
@jdat82 that is not a gulp issue

**Comment by jdat82** [comment]
So I guess you have the same latency and it is just "normal". Is it due to the babel processing ? My gulp file is only an hello world. It seems very slow for just a few lines.
