### ISSUE TITLE
'Occurred'

### ISSUE THREAD

**Issue by xHeliotrope** [gulpjs/gulp#1385]
[13:49:10] Starting 'client:build'...
[13:49:10] 'client:build' errored after 316 ms
[13:49:10] TypeError: $.useref.restore is not a function
    at Gulp.<anonymous> (/Users/nonzero/Programming/testing/gulpfile.js:171:20)
    at module.exports (/Users/nonzero/Programming/testing/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/nonzero/Programming/testing/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/nonzero/Programming/testing/node_modules/orchestrator/index.js:214:10)
    at /Users/nonzero/Programming/testing/node_modules/orchestrator/index.js:279:18
    at finish (/Users/nonzero/Programming/testing/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/nonzero/Programming/testing/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/nonzero/Programming/testing/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/nonzero/Programming/testing/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at /Users/nonzero/Programming/testing/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
[13:49:10] Error in plugin 'run-sequence'
Message:
    An error occured in task 'client:build'.
[13:49:10] Finished 'images' after 806 ms

**Comment by TrySound** [comment]
@xHeliotrope Show your code

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
