### ISSUE TITLE
Error: Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by v3nt** [gulpjs/gulp#1390]
I've tried re-installing several times and removed npm_module folders from the local install and global install but no joy. 

Using OS X el capitan.

npm -v
3.3.5

gulp -v
module.js:338
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:4:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

**Comment by callumacrae** [comment]
Have you ran `npm install --save-dev gulp-util`?

**Comment by v3nt** [comment]
yep - several times and as sudo. Same problem all the time.

**Comment by phated** [comment]
This is a problem with your environment or installation using npm.  This is not a gulp issue.

**Comment by v3nt** [comment]
thanks phated - grunt and everything else nom wise is working fine. DO have a suggestion how i can prove or rule out a problem with the environment?

**Comment by v3nt** [comment]
tried re-installing as sudo too but still get - 

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "gulp"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! path /Users/jynk/.npm-packages/lib/node_modules/gulp/node_modules/camelcase
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/jynk/.npm-packages/lib/node_modules/gulp/node_modules/camelcase'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/jynk/.npm-packages/lib/node_modules/gulp/node_modules/camelcase']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/jynk/.npm-packages/lib/node_modules/gulp/node_modules/camelcase' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jynk/Projects/634 Reform Architects/website/reform-website-master/wp-content/themes/reform/npm-debug.log
JYNK-IMAC-RET:reform jynk$ sudo npm install --global gulp
Password:
/Users/jynk/.npm-packages/bin/gulp -> /Users/jynk/.npm-packages/lib/node_modules/gulp/bin/gulp.js
/Users/jynk/.npm-packages/lib
└─┬ gulp@3.9.0 
  └─┬ gulp-util@3.0.7
    └─┬ dateformat@1.0.11
      └─┬ meow@3.6.0 
        ├─┬ camelcase-keys@2.0.0 
        │ └── camelcase@2.0.0 
        └─┬ read-pkg-up@1.0.1
          ├─┬ find-up@1.1.0 
          │ ├── path-exists@2.1.0 
          │ └─┬ pinkie-promise@2.0.0 
          │   └── pinkie@2.0.0 
          └─┬ read-pkg@1.1.0
            ├── load-json-file@1.1.0 
            └── path-type@1.1.0 

JYNK-IMAC-RET:reform jynk$ gulp
module.js:338
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:4:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
