### ISSUE TITLE
gulp.src doesn't match wildcard

### ISSUE THREAD

**Issue by 190n** [gulpjs/gulp#1412]
`gulp.src` is only matching three files in a glob.

`gulpfile.js`:

```js
var gulp = require('gulp'),
    babel = require('gulp-babel'),
    browserify = require('browserify'),
    source = require('vinyl-source-stream');

gulp.task('default', function() {
    gulp.src('./lib/*.js')
        .pipe(babel())
        .pipe(gulp.dest('build/'));
    return browserify('build/main.js')
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(gulp.dest('build/'));
});
```

Files in `lib`: base-entity.js	compound-entity.js  constants.js  image-entity.js  invader.js  invader-manager.js  main.js  manager.js	movement.js  tank.js  text-entity.js

Running `gulp`:

```
[14:10:35] Using gulpfile ~/code/js/nueva-my-page/gulpfile.js
[14:10:35] Starting 'default'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/home/ben/code/js/nueva-my-page/build/main.js' from '/home/ben/code/js/nueva-my-page'
    at /home/ben/code/js/nueva-my-page/node_modules/resolve/lib/async.js:55:21
    at load (/home/ben/code/js/nueva-my-page/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ben/code/js/nueva-my-page/node_modules/resolve/lib/async.js:92:31)
    at /home/ben/code/js/nueva-my-page/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Files in `build` after that: base-entity.js compound-entity.js constants.js

If I pass in an array of all the files, it still doesn't work. But it does work if I do it for each file individually.

**Comment by doowb** [comment]
The `browserify('build/main.js')` piece is going to start immediately, so the first statement might be finished writing the files to `build/`.

Try splitting this into 2 tasks and making one a dependency of the other...

```js
var gulp = require('gulp'),
    babel = require('gulp-babel'),
    browserify = require('browserify'),
    source = require('vinyl-source-stream');

gulp.task('build', function() {
  return gulp.src('./lib/*.js')
    .pipe(babel())
    .pipe(gulp.dest('build/'));
});

gulp.task('bundle', ['build'], function() {
  return browserify('build/main.js')
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('build/'));
});

gulp.task('default', ['bundle']);
```

**Comment by 190n** [comment]
Okay. Thanks!
