### ISSUE TITLE
Cannot find module 'clone' (Gulp 3.9.0 and NodeJS 5.1.0)

### ISSUE THREAD

**Issue by cmayo** [gulpjs/gulp#1413]
I've recently updated to node v5.1.0 in my MacOSX 10.10 and now I'm trying to run gulp in my project and I get this error:

```
module.js:340
    throw err;
    ^

Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/<MYFOLDER>/node_modules/defaults/index.js:1:75)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
I've cleared the npm cache and reinstalling globally glup `sudo npm install -g gulp` and reinstalled all my project node modules `npm install`and the error is still there. I can't execute any gulp task.

**Comment by phated** [comment]
Something is wrong with your install. This isn't a gulp problem, most likely a problem with your environment or npm.

**Comment by Ryangr0** [comment]
Having the same issue, except I'm not on OSX. @cmayo would you mind sharing your solution? If you've found one, that is.
