### ISSUE TITLE
option-manager.js:411     });     SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by mxc** [gulpjs/gulp#1432]
Hi all,

I am trying to compile a project which worked fine under node v4.2.2 under node v5.1.1 and I am getting the following error:

    gulp
    .../node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:411
    });
    SyntaxError: Unexpected token )
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:404:25)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/.../cauldron-master/node_modules/gulp-   babel/node_modules/babel-core/lib/api/node.js:41:47)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)

I have the following task configured:

    gulp.task('js', function () {
        return gulp.src('src/*.js')
                .pipe(babel({
                    "presets": ['es2015', 'react']
                }))
                .pipe(gulp.dest('build/js'));
    });

I think this is the task causing the problem. Not sure how else to troubleshoot this.

**Comment by Romanx** [comment]
Looks like it's a [gulp-babel](https://github.com/babel/gulp-babel) issue rather than a gulp one.

**Comment by mxc** [comment]
Thanks - will log t there.
