### ISSUE TITLE
 Cannot find module 'clone-stats'

### ISSUE THREAD

**Issue by DWboutin** [gulpjs/gulp#1435]
I just updated my Gulp and this happened:

```
Error: Cannot find module 'clone-stats'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\Mike\AppData\Roaming\npm\node_modules\gulp\node_modules\vinyl\index.js:3:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
```

**Comment by contra** [comment]
reinstall, not a gulp issue - npm fails all the time

**Comment by DWboutin** [comment]
I did reinstall once, it doesn't work... I remove all the global node_modules from app/roaming/... and reinstall node and it worked!
