### ISSUE TITLE
Gulp throw error when run the command

### ISSUE THREAD

**Issue by 3gwebtrain** [gulpjs/gulp#1447]
I am getting `error` while running the gulp. but I am not able to figureout the issue. any one help me please?

here is my error :

```javascript

D:\Projects\angular2>gulp
[10:46:12] Using gulpfile D:\Projects\angular2\gulpfile.js
[10:46:12] Starting 'tsc-compile'...
[10:46:14] Finished 'tsc-compile' after 2.71 s
[10:46:14] Starting 'serve'...
[10:46:14] 'serve' errored after 1.41 ms
[10:46:14] TypeError: Cannot read property 'indexOf' of undefined
    at D:\Projects\angular2\node_modules\globule\lib\globule.js:25:16
    at Array.reduce (native)
    at processPatterns (D:\Projects\angular2\node_modules\globule\lib\globule.js
:24:30)
    at Object.globule.find (D:\Projects\angular2\node_modules\globule\lib\globul
e.js:76:17)
    at Gaze.add (D:\Projects\angular2\node_modules\gaze\lib\gaze.js:174:19)
    at new Gaze (D:\Projects\angular2\node_modules\gaze\lib\gaze.js:74:10)
    at gaze (D:\Projects\angular2\node_modules\gaze\lib\gaze.js:86:10)
    at Object.module.exports [as watch] (D:\Projects\angular2\node_modules\glob-
watcher\index.js:12:17)
    at Gulp.watch (D:\Projects\angular2\node_modules\gulp\index.js:35:16)
    at Gulp.<anonymous> (D:\Projects\angular2\gulpfile.js:26:7)

```

and here is my `gulpfile.js` :

```javascript

var gulp = require('gulp');
var sourcemaps	= require('gulp-sourcemaps');
var tsc 	= require('gulp-typescript');
var tscConfig = tsc.createProject("tsconfig.json");
var gulpConfig = require('./gulp.config')();

var browserSync = require('browser-sync');
var superstatic = require('superstatic');


gulp.task('tsc-compile', function () {

	var tsFiles = [ gulpConfig.allTs ]
		
	var result = gulp.src(tsFiles)
				.pipe(sourcemaps.init())
				.pipe(tsc(tscConfig));

	return result.js
			.pipe(sourcemaps.write('.'))
			.pipe(gulp.dest(gulpConfig.outputPath));

});


gulp.task('serve', function(){

	gulp.watch([tscConfig.allTs], ['tsc-compile'] );//if i comment this no error throws. But nothing watched.

	browserSync({
		port:3000,
		file:['index.html', '**/*.js'],
		injectChanges:true,
		logFileChanges:false,
		logLevel:'silent',
		notify:true,
		reloadDelay:0,
		server:{
			middleware:superstatic({debug:false})
		}
	})

})

gulp.task('default', ['serve']);

```

**Comment by Romanx** [comment]
You're getting an error from gaze `at gaze (D:\Projects\angular2\node_modules\gaze\lib\gaze.js:86:10)` which is used in the gulp.watch in v3.0+ The since the error message is `TypeError: Cannot read property 'indexOf' of undefined` `at Array.reduce (native)` 

I'm going to guess that `tscConfig.allTs` doesn't have a value at that point or is null? Have a look at that, also support questions should directed to StackOverflow, Github is primarily used as a issue tracker for gulp bugs, errors and features.

**Comment by phated** [comment]
Thanks @Romanx for answering this.
