### ISSUE TITLE
Gulp 4: `done is not a function` during watch task

### ISSUE THREAD

**Issue by CodeTheory** [gulpjs/gulp#1448]
Hi there.

I'm getting this error when changing a file whilst running a watch task. I wasn't sure whether to submit it as an issue as I can't find anyone having a similar issue so it may just be my fault. Could someone point me in the right direction, here?

Here is my gulpfile: https://gist.github.com/CodeTheory/f2cbf01a267bec6b9991

--
`gulp -v`
```
[14:37:54] CLI version 1.1.0
[14:37:54] Local version 4.0.0-alpha.2
```

--
`gulp --continue`
```
[14:29:10] Failed to load external module babel-register
[14:29:10] Requiring external module babel-core/register
[14:30:55] Using gulpfile ~/Sites/gasket/homepage/gulpfile.babel.js
[14:30:55] Starting 'default'...
[14:30:55] Starting 'clean'...
Removed public.
[14:30:55] Finished 'clean' after 73 ms
[14:30:55] Starting '<parallel>'...
[14:30:55] Starting 'build:views'...
[14:30:55] Starting 'build:styles'...
[14:30:55] Starting 'build:scripts'...
[14:30:55] Starting 'build:fonts'...
[14:30:55] Starting 'build:vendor'...
[14:30:55] Starting 'build:images'...
[14:30:55] Starting 'build:svgSprite'...
[14:30:56] Finished 'build:scripts' after 320 ms
[14:30:56] Finished 'build:fonts' after 371 ms
[14:30:56] Finished 'build:svgSprite' after 372 ms
[14:30:56] Finished 'build:vendor' after 568 ms
[14:30:56] Finished 'build:views' after 651 ms
[14:30:56] Finished 'build:images' after 813 ms
[14:30:57] Finished 'build:styles' after 1.37 s
[14:30:57] Finished '<parallel>' after 1.37 s
[14:30:57] Starting 'inject:livereload'...
[14:30:57] Finished 'inject:livereload' after 22 ms
[14:30:57] Starting 'watch'...
[14:31:18] Starting '<series>'...
[14:31:18] Starting 'build:styles'...
[14:31:18] /Users/timothy/Sites/gasket/homepage/public/stylesheets/app.min.css reloaded.
[14:31:19] /Users/timothy/Sites/gasket/homepage/public/stylesheets/main.min.css reloaded.
[14:31:19] Finished 'build:styles' after 745 ms
[14:31:19] Finished '<series>' after 746 ms
[14:31:19] The following tasks did not complete: default, watch
[14:31:19] Did you forget to signal async completion?
/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/lib/helpers.js:34
    done(errors, results);
    ^

TypeError: done is not a function
    at onSettled (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/lib/helpers.js:34:5)
    at f (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at handler (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/map.js:53:9)
    at f (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at /Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-settle/index.js:17:5
    at f (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-settle/node_modules/async-done/node_modules/once/once.js:17:25)
    at done (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-settle/node_modules/async-done/index.js:26:12)
    at onSettled (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/lib/helpers.js:34:5)
    at f (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at handler (/Users/timothy/Sites/gasket/homepage/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/mapSeries.js:51:9)
```

I'm sorry if this is the wrong place or I've conditioned this issue incorrectly. Please let me know if I can provide any more information.

**Comment by phated** [comment]
gulp-if needs to go in a pipeline. It returns a stream and also can't be used with task strings. Support questions should be directed to StackOverflow

**Comment by CodeTheory** [comment]
Thanks @phated. I didn't know if this was a support question of a problem from gulp.

Thank you for taking time to reply.
