### ISSUE TITLE
An error or a notice? - throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Soufraz** [gulpjs/gulp#1479]
Is there a 'fatal error'? Need I fix this? What is wrong? Is there a verbose param to see what is wrong?

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: undefined:925:29: missing '}'
    at error (/home/user/project/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/home/user/project/node_modules/css/lib/parse/index.js:259:26)
    at rule (/home/user/project/node_modules/css/lib/parse/index.js:560:21)
    at rules (/home/user/project/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/home/user/project/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/home/user/project/node_modules/css/lib/parse/index.js:564:20)
    at rework (/home/user/project/node_modules/rework/index.js:27:21)
    at DestroyableTransform._transform (/home/user/project/node_modules/gulp-concat-css/index.js:82:22)
    at DestroyableTransform.Transform._read (/home/user/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/user/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

**Comment by phated** [comment]
Please read your stack trace. This is a syntax problem in your css. Support questions should be directed to StackOverflow

**Comment by Procaseycash** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: Line 62998: Unexpected token ILLEGAL
    at constructError (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:2407:21)
    at createError (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:2426:17)
    at unexpectedTokenError (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:2501:13)
    at throwUnexpectedToken (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:2505:15)
    at scanPunctuator (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:842:13)
    at advance (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:1622:16)
    at collectToken (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:1635:17)
    at lex (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:1691:61)
    at consumeSemicolon (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:2606:13)
    at parseStatement (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:4816:9)
    at parseStatementListItem (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:3989:16)
    at parseScriptBody (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:5490:25)
    at parseProgram (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:5506:16)
    at Object.parse (C:\Users\SQ05\eclipse_sd\zeus\node_modules\esprima\esprima.js:5690:23)
    at Object.parse (C:\Users\SQ05\eclipse_sd\zeus\node_modules\rocambole\rocambole.js:50:23)
    at Object.moonwalk (C:\Users\SQ05\eclipse_sd\zeus\node_modules\rocambole\rocambole.js:397:23)
