### ISSUE TITLE
Cannot find module 'lodash.template' on gulp@3.9.1

### ISSUE THREAD

**Issue by PawelGIX** [gulpjs/gulp#1520]
node v5.4.1
gulp@3.9.1

```
  throw err;
    ^

Error: Cannot find module 'lodash.template'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/lib/template.js:1:78)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by piyushchauhan2011** [comment]
Not getting this error maybe update to node 5.5 @PawelGIX

**Comment by PawelGIX** [comment]
Unfortunately after update, it did not help. Still the same error.
But after: 
`rm -rf node_modules && npm cache clean && npm i gulp && npm i -g gulp` 

works well
