### ISSUE TITLE
[gulp 4] Error: Uncaught, unspecified "error" event with node 4.3.2

### ISSUE THREAD

**Issue by timaschew** [gulpjs/gulp#1552]
I used all the time nodejs 5.4.1, but node-inspectory didn't work, so I switch to node.js 4.3.2 (of course aI deleted the node_modules) but now I get this error, regardless if I start with node-inspector or directly

events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Gulp.emit (events.js:144:17)
    at Object.error (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/mapSeries.js:43:14)
    at f (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at f (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/node_modules/once/once.js:17:25)
    at done (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:24:15)
    at Domain.onError (/Users/anton/dev/o/html-templates/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:32:12)
    at Domain.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)

**Comment by tunnckoCore** [comment]
Can you give a code example?

**Comment by phated** [comment]
Definitely needs more context...  I'm fine with leaving it here

**Comment by phated** [comment]
@timaschew looking for more information

**Comment by timaschew** [comment]
cannot reproduce it anymore
