### ISSUE TITLE
Errors generated by Karma (w/ Webpack preprocessor) not properly bubbling up to console

### ISSUE THREAD

**Issue by jcfrancisco** [gulpjs/gulp#1559]
Howdy – noticed this bug after we upgraded a project to Gulp 4.0.

Assuming you have a spec with a syntax error or incorrectly named import statement, and the following config files:

`gulpfile.js`:
```
var KarmaServer = require('karma').Server;

gulp.task('test', function(cb) {
  new KarmaServer({
    configFile: __dirname + '/karma.conf.js'
  }, cb).start();
});
```

`karma.conf.js`:
```
module.exports = function(config) {
  config.set({
    ...
    preprocessors: {
      'spec/*.js': ['webpack']
    },
    ...
  });
}
```

**Output when running `gulp test` on `gulp@3.9.x`:**
```
[14:52:05] Using gulpfile ~/karma-webpack-error-demo/gulpfile.js
[14:52:05] Starting 'test'...
11 03 2016 14:52:05.114:DEBUG [plugin]: Loading karma-* from /Users/pivotal/karma-webpack-error-demo/node_modules
11 03 2016 14:52:05.116:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-chrome-launcher.
11 03 2016 14:52:05.119:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-mocha.
11 03 2016 14:52:05.120:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack.
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.14
Time: 11ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
11 03 2016 14:52:05.392:ERROR [karma]: { [Error: no such file or directory]
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/spec/has_no_syntax_error.js' }
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/pivotal/karma-webpack-error-demo/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
    at MemoryFileSystem.readFile (/Users/pivotal/karma-webpack-error-demo/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (/Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack/index.js:160:3)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
11 03 2016 14:52:05.410:DEBUG [launcher]: Disconnecting all browsers
Hash: 87847b53bcc1b2440cb6
Version: webpack 1.12.14
Time: 17ms
                   Asset     Size  Chunks             Chunk Names
spec/has_syntax_error.js  1.52 kB       0  [emitted]  spec/has_syntax_error.js
chunk    {0} spec/has_syntax_error.js (spec/has_syntax_error.js) 108 bytes [rendered]
    [0] ./spec/has_syntax_error.js 108 bytes {0} [built]

ERROR in ./spec/has_no_syntax_error.js
Module parse failed: /Users/pivotal/karma-webpack-error-demo/spec/has_no_syntax_error.js Line 6: Unexpected end of input
You may need an appropriate loader to handle this file type.
|   //});
| });
|
webpack: bundle is now VALID.
[14:52:05] 'test' errored after 306 ms
[14:52:05] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/pivotal/karma-webpack-error-demo/node_modules/orchestrator/index.js:264:8)
    at /Users/pivotal/karma-webpack-error-demo/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pivotal/karma-webpack-error-demo/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pivotal/karma-webpack-error-demo/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/pivotal/karma-webpack-error-demo/node_modules/karma/lib/server.js:336:7)
    at /Users/pivotal/karma-webpack-error-demo/node_modules/karma/lib/server.js:347:9
    at Server.<anonymous> (net.js:1480:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1527:8)
    at _combinedTickCallback (node.js:374:13)
```

**Output when running `gulp test` on `gulp@4.0.0-alpha.2`:**

```
14:47:52] Using gulpfile ~/karma-webpack-error-demo/gulpfile.js
[14:47:53] Starting 'test'...
11 03 2016 14:47:53.005:DEBUG [plugin]: Loading karma-* from /Users/pivotal/karma-webpack-error-demo/node_modules
11 03 2016 14:47:53.007:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-chrome-launcher.
11 03 2016 14:47:53.012:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-mocha.
11 03 2016 14:47:53.012:DEBUG [plugin]: Loading plugin /Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack.
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.14
Time: 8ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
[14:47:53] 'test' errored after 186 ms
[14:47:53] Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/pivotal/karma-webpack-error-demo/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
    at MemoryFileSystem.readFile (/Users/pivotal/karma-webpack-error-demo/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (/Users/pivotal/karma-webpack-error-demo/node_modules/karma-webpack/index.js:160:3)
    at _combinedTickCallback (node.js:370:9)
    at process._tickDomainCallback (node.js:425:11)
```

Demo repo here: https://github.com/jcfrancisco/karma-webpack-error-demo
(Sorry for the pseudo-tags in the title -- wanted to clarify that this only seems to be a bug with 4.0.)

This isn't a huge issue since the syntax error can be found with a linter, or by running Karma from the command line. However, it would help us a lot if the error output were verbose like it is in 3.9.x!

**Comment by phated** [comment]
@jcfrancisco it looks like there's 2 different errors between the examples.  What is the expected outcome here?

**Comment by jcfrancisco** [comment]
@phated What's ultimately happening in both cases is the same: Karma fails to find the Webpack-preprocessed spec file, because the preprocessing step fails to generate that spec file. Note how both snippets include a `could not find file or directory` log.

The difference is that when run through gulp, the error message generated by the faulty preprocessing step is omitted (even though it's still happening), whereas when run without gulp, the error is printed (a botched `import` statement -- the part that says `module parse failed`).

**Comment by phated** [comment]
@jcfrancisco I was able to track down some more information about this but I'm not sure the best way to solve.  This is happening in gulp 4 because of the new task system.  With the old task system, if anything was keeping the process open (here, it is the karma server), the task would never fail because the process would never exit.  With the new task system, we use `process.exit(1)` right when the error occurs (and our callback is called with it).

Each task is executed on `nextTick`, which makes the entire set of tasks async and thusly, our callback is called async; however, that callback is called sync from inside the task that fails, so we immediately kill the process and the karma server doesn't get a chance to report the errors as with gulp 3 (remember, it kept it open forever).

The way I was able to get your logs to show up was by using `nextTick` around the `process.exit(1)` call, but I'm not sure if that is a band-aid or the correct fix.  I'm not sure if I should be `nextTick`ing the final callback to the set of tasks or just that exit or if this even needs to be fixed (since once you fix one error, the next will be logged and the process will exit).

Does anyone have any thoughts about all this?

**Comment by jcfrancisco** [comment]
Interesting, thanks for the detailed investigation!!

I might be totally off-base here since I don't really know how the new task system works, but I wonder if instead of calling the synchronous `process.exit(1)`, we could pass an error into the callback and bail out of the process further up the call stack, when we have all the errors generated by all the tasks.

**Comment by phated** [comment]
@jcfrancisco we are logging all errors that are passed to callbacks but the thing you are seeing is being logged internally by your karma runner.  I think this problem is fundamentally a karma problem and maybe we shouldn't change anything.

**Comment by phated** [comment]
As stated above, I think this is a karma runner problem and not a gulp problem.  Historically, there have been many things the karma runner has done incorrectly so I'm not going to change anything here.
