### ISSUE TITLE
Error: Cannot find module './plugins/plugins/plugins.plugin'

### ISSUE THREAD

**Issue by sclanc** [gulpjs/gulp#1584]
Alright, My gulp set up as been working excellently for a while now,  and I love using it, but I seem to have run into a problem all of a sudden: here is the full text of the Terminal error.
`Error: Cannot find module './plugins/plugins/plugins.plugin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sean/dev/frontend/epr/node_modules/browser-sync/node_modules/browser-sync-ui/lib/UI.js:14:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
`
and here is a history of commands that I used to try and correct the situation: 
 
gulp serve - here I tried to serve and got 'Error: Cannot find module 'strip-ansi''
 1084  npm --version
 1085  npm install strip-ansi
 1086  gulp serve -here I got 'Error: Cannot find module 'has-ansi''
 1087  npm install has-ansi
 1088  gulp serve -here I got 'Error: Cannot find module 'supports-color''
 1089  npm install supports-color
 1090  gulp serve 
 1091  npm install ./plugins/plugins/plugins.plugin (I'm pretty sure that's not a thing, but I tried it anyway)
 1092  gulp serve
 1093  npm install gulp
 1094  gulp serve
 1095  bower install
 1096  gulp serve

I hope this isn't a bothersome question, I am still pretty new to npm and gulp. Any advice that you might have would be very much appreciated.

**Comment by sclanc** [comment]
Update, I am still able to serve other projects with gulp so it is likely an issue with this project, I haven't made any substantial changes to the gulp file but would that even cause this kind of problem?
Thanks again?.

**Comment by sclanc** [comment]
This issue was solved by executing: 

`sudo npm install browser-sync `

in the terminal at my project directory's location, I will link this issue to Browser Sync's documentation and close this issue.
