### ISSUE TITLE
need help with systemjs when using gulp-jasmine

### ISSUE THREAD

**Issue by HeavenlyHost** [gulpjs/gulp#1618]
So I may be new to this thing, but I am trying to use gulp to build, lint and test my demo solution. The app is using Angular 2, Gulp, SystemJS, gulp-tslint and gulp-jasmine, however I am unable to get the gulp-jasmine to run without falling over. It complains with the following

 events.js:141
      throw er; // Unhandled 'error' event
      ^
 TypeError: Invalid System.register call. Anonymous System.register calls can on
ly be made by modules loaded by SystemJS.import and not via script tags.
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:2981:17)
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:3655:29)
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:4142:33)
    at SystemJSNodeLoader.reduceRegister_ (D:\ng2demo\node_modules\systemjs\dist
\system.src.js:4142:33)
    at SystemJSNodeLoader.pushRegister_ (D:\ng2demo\node_modules\systemjs\dist\s
ystem.src.js:2699:14)
    at SystemJSNodeLoader.SystemJSLoader.register (D:\ng2demo\node_modules\syste
mjs\dist\system.src.js:2937:10)
    at Object.<anonymous> (D:\ng2demo\app\assets\services\config.service.spec.js
:4:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

The JS file it is attempting to run is a spec written in TypeScript and transpiled to JS with gulp-typescript. So the top line of the file is...

System.register(['angular2/core', 'angular2/http', 'angular2/http/testing', './config.service'], function(exports_1, context_1) {
//Do Stuff
});

It is this line it has a problem with, any ideas ???

**Comment by TrySound** [comment]
@HeavenlyHost It's not gulp issue. Please direct support questions to StackOverflow or gulp-jasmine issues.
