### ISSUE TITLE
Rejected Promises w/o values should cause tasks to fail

### ISSUE THREAD

**Issue by jeffposnick** [gulpjs/gulp#1642]
Returning a rejected (native) `Promise` from within a task will not cause that task to fail unless the rejected `Promise` has a value. For example, I'd naively expect both of the following tasks to fail, but the `no-reason` task is considered a success:

```js
gulp.task('no-reason', () => {
  return Promise.reject();
});

gulp.task('reason', () => {
  return Promise.reject('This task does fail.');
});
```

I can reproduce this behavior with v3.9.1.

I can understand why an error value is needed with the callback approach to asynchronous tasks, but there's success/failure state stored within the `Promise` object itself, I'd think that any rejection should be treated as a failure.

**Comment by phated** [comment]
This has been fixed in 4.0, please upgrade.

**Comment by jeffposnick** [comment]
It doesn't seem to be fixed:

```js
// Inside gulpfile.js:
const gulp = require('gulp');

gulp.task('reject-without-value', () => Promise.reject());
gulp.task('reject-with-value', () => Promise.reject('rejection reason'));
```

```sh
$ gulp -v
[14:52:22] CLI version 1.3.0
[14:52:22] Local version 4.0.0-alpha.2
```

```sh
$ gulp reject-without-value
[14:52:30] Using gulpfile /private/tmp/b/gulpfile.js
[14:52:30] Starting 'reject-without-value'...
[14:52:30] Finished 'reject-without-value' after 2.16 ms
$ echo $?
0
```

```sh
$ gulp reject-with-value
[14:52:37] Using gulpfile /private/tmp/b/gulpfile.js
[14:52:37] Starting 'reject-with-value'...
[14:52:37] 'reject-with-value' errored after 1.85 ms
[14:52:37] Error: rejection reason
    at formatError (/Users/jeffy/homebrew/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/formatError.js:20:10)
    at Gulp.<anonymous> (/Users/jeffy/homebrew/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:30:15)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Object.error (/private/tmp/b/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/private/tmp/b/node_modules/now-and-later/lib/map.js:46:14)
    at f (/private/tmp/b/node_modules/once/once.js:25:25)
    at f (/private/tmp/b/node_modules/once/once.js:25:25)
    at done (/private/tmp/b/node_modules/async-done/index.js:24:15)
    at onError (/private/tmp/b/node_modules/async-done/index.js:32:12)
$ echo $?
1
```

**Comment by phated** [comment]
@jeffposnick You're right - it's due to this line: https://github.com/gulpjs/async-done/blob/master/index.js#L31-L33

Can you open this issue on the `async-done` repo (a failing test case would be awesome too).

**Comment by jeffposnick** [comment]
Filed https://github.com/gulpjs/async-done/issues/42

Thanks for continuing to work on `gulp` 4!
