### ISSUE TITLE
Can not pipe gulp's STDERR

### ISSUE THREAD

**Issue by EvanCarroll** [gulpjs/gulp#1679]
Demonstration
====

```bash
mkdir /tmp/asdf;
cd /tmp/asdf;
npm init -f;
npm install --save-dev gulp;
touch gulpfile.js;
$(npm bin)/gulp 2| less;
```

**NOTICE THE USE** of `2| less`. This is required. This is the bug.

Output
====

```text
[19:48:24] Using gulpfile /tmp/asdf/gulpfile.js
(node:3985) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/tmp/asdf/node_modules/orchestrator/index.js:89
                                        throw new Error('pass strings or arrays of strings');
                                        ^

Error: pass strings or arrays of strings
    at Gulp.Orchestrator.start (/tmp/asdf/node_modules/orchestrator/index.js:89:12)
    at /tmp/asdf/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

Seems as if gulp can't have STDERR redirected by bash to a fifo.

**Comment by phated** [comment]
Unable to replicate.  The logs go to stderr for me.  The error you pasted isn't generated by an empty gulpfile.  If you continue to experience this problem, I suggest you switch to `gulp-cli` which is the new CLI module that supports both gulp 3.x and 4.
