### ISSUE TITLE
gulp 3.9.1 throws error when using gulpfile.babel.js

### ISSUE THREAD

**Issue by nerdgore** [gulpjs/gulp#1680]
Upgrading to gulp@3.9.1 I receive the following error message:

```
[11:55:09] Requiring external module babel-register
/workspace/my_app/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import env from "node-env-file";

                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at loader (/workspace/my_app//node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/my_app/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/workspace/my_app/node_modules/gulp/bin/gulp.js
```

Running 3.9.0 with this setup or using `babel-node gulp` works perfectly fine.

contents of gulp file.babel.js

```javascript
import env from "node-env-file";
import gutil from "gulp-util";
import loadTasks from "gulp-load-tasks";

// load dev properties into process.env
env("src/main/resources/dev.properties");

loadTasks("scripts/tasks");

if (process.env.npm_config_buildEnv) {
    gutil.log(`Building for ${gutil.colors.magenta(process.env.npm_config_buildEnv)}`);
} else {
    gutil.log("No npm buildEnv peroperty provided");
    gutil.log(gutil.colors.magenta("Running in dev mode!"));
}
```

**Comment by callumacrae** [comment]
Click "require hook" and read the section on .babelrc here: http://babeljs.io/docs/setup/#installation

Any further issues, please take it up with babel: this isn't a gulp issue!

**Comment by moravcik** [comment]
I had the same issue, my `gulp.babel.js` stopped working after grabbed the new 3.9.1 version. 
As I found I forgit to commit `.babelrc` into git, so it was missing in the production build process.
Seems gulp <3.9.1 was using some default preset for babel which was removed with the new version.

**Comment by mzvast** [comment]
add a .babelrc file with these stuff:
```
{
  "presets": ["es2015"],
  // Remove the line below to enable ES2015 support.
//   "only": "gulpfile.babel.js",
  "retainLines": true
}

```

**Comment by selrond** [comment]
Why do I need to rename `gulpfile.js` to `gulpfile.babel.js`? Can't find anything related to that in Babel's docs
