### ISSUE TITLE
This is what I got, while running gulp

### ISSUE THREAD

**Issue by imrealashu** [gulpjs/gulp#1700]
/home/vagrant/Code/project/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:99
  this.readableListening
                        
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Code/project/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:29:16)
    at Module._compile (module.js:541:32)

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
