### ISSUE TITLE
gulp command is not running

### ISSUE THREAD

**Issue by simoziyadi** [gulpjs/gulp#1703]
I have installed gulp globaly on my windows and locally in my project however when i run the gulp command i get this error : 

module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\wamp(php5.6)\wamp64\www\dento\Denteo\src\Denteo\Bu
ndle\PatientBundle\Resources\public\gulpfile.js:2:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Deos anyone knows what could be the source of this problems:

Thanks for answering.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
