### ISSUE TITLE
[gulp 4] Watcher bug with the same names

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [gulpjs/gulp#1732]
```js
var gulp = require('gulp');

gulp.task("default", function() {
  return gulp.watch("src/**/*.x", function(done) {
     console.log("Do stuff");
     done();
  });
});
```

1. Start files watcher with `src/**/*.x` globs.
2. Create new file `randomname.x`
3. Create new folder with the same name `randomname` (without extension)
4. Delete folder `randomname`

When folder deleted or created, watcher emit change with globs `src/**/*.x`

Output:
```cmd
[19:10:39] Starting 'default'...
[19:10:45] Starting '<anonymous>'...
Do stuff
[19:10:45] Finished '<anonymous>' after 2.88 ms
[19:10:57] Starting '<anonymous>'...
Do stuff
[19:10:57] Finished '<anonymous>' after 2.78 ms
[19:10:59] 'default' errored after 21 s
[19:10:59] Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1008:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

**Comment by phated** [comment]
Looking at the stack trace, this would be a chokidar issue.  Please open the issue on their tracker.
