### ISSUE TITLE
Error: Cannot find module 'gulp-if'

### ISSUE THREAD

**Issue by sruj** [gulpjs/gulp#1756]
command :

> $ sudo npm run gulp

display:

```
Error: Cannot find module 'gulp-if'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/sylius/Gulpfile.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

command :

> gulp

display:
```
module.js:340
    throw err;
    ^
Error: Cannot find module 'gulp-if'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/sylius/Gulpfile.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

```

**Comment by Arial7** [comment]
What's your node version?

**Comment by sruj** [comment]
v0.10.25

**Comment by contra** [comment]
You're using it in your gulpfile and you don't have it installed. The error is pretty clear, you need to install it.

**Comment by Arial7** [comment]
I still think you should nevertheless update models, as 0.10 is _very_ old.

**Comment by phated** [comment]
@Arial7 it's still the most stable version of node and your comment has nothing to do with the problem.

@sruj Support questions should be directed to StackOverflow.
