### ISSUE TITLE
gulp4 es6 (typescript) not transpiling

### ISSUE THREAD

**Issue by dima-gusyatiner** [gulpjs/gulp#1819]
Hi,

This is a clean install, only installed:
```
npm ls --depth=0
app@0.1.0 C:\localhost\dima-01
+-- gulp@4.0.0-alpha.2 (git://github.com/gulpjs/gulp.git#d8f5c90a0622d19ef1943a2a3d02dc50e3c853e7)
```
On the machine I have windows10 x64, and global packages as follows:
```
$ node -v && npm -v
v6.6.0
3.10.8
```
...and (terribly slow `npm ls -g` that made me manually remove the whole 1GB):
```
$ npm ls -g --depth=0 gulp typescript ts-node
```

I was trying to use the es6 syntax, nothing fancy, just:
```js
import gulp from 'gulp';
```

You claim to have typescript support out-of-the box when running `gulp`, but instead I get this error:
```
$ gulp
[06:01:40] Failed to load external module ts-node/register
[06:01:40] Failed to load external module typescript-node/register
[06:01:40] Failed to load external module typescript-register
[06:01:40] Failed to load external module typescript-require
C:\localhost\dima-01\gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at execute (C:\Users\Dima\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.2\index.js:35:18)
    at Liftoff.handleArguments (C:\Users\Dima\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js:149:63)
```
From the error I understand that the problem is in transpiling.

This happens with and without `tsconfig.json` in the project folder.
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
  }
}
```

Executing `ts-node gulpfile` outputs `1`, hence it's not the transpiler itself.

**Comment by phated** [comment]
Your transpiler isn't installed locally. You seem to have missed the section in our issue template that says "Support questions should be directed to StackOverflow".
