### ISSUE TITLE
gulp watch error however gulp build works fine - Windows 10 Ubuntu Bash

### ISSUE THREAD

**Issue by darthvader666uk** [gulpjs/gulp#1852]
Hi,

THis might not be the correct place for this but seem to be having specifically using Ubuntu Bash on Windows 10.

I can "gulp build" without any issues but If i "gulp watch" I awlays get the following:

[16:19:46] Using gulpfile /mnt/d/Work/Dev/work/gulpfile.js
[16:19:46] Starting 'watch'...
[16:19:46] 'watch' errored after 70 ms
[16:19:46] Error: watch /mnt/d/Work/Dev/work/src/modules/advanced/ EPERM
    at exports._errnoException (util.js:907:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Gaze._watchDir (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/mnt/d/Work/Dev/work/node_modules/gulp/index.js:35:16)
    at Gulp.<anonymous> (/mnt/d/Work/Dev/work/gulpfile.js:304:7)
    at module.exports (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/mnt/d/Work/Dev/work/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)

I Have even tried the following solution:

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

THis is the response I have:

fs.inotify.max_user_watches=524288
sysctl: cannot stat /proc/sys/fs/inotify/max_user_watches: No such file or directory
sysctl: cannot stat /proc/sys/fs/inotify/max_user_watches: No such file or directory

Though if I look in "/etc/sysctl.conf" I can see it actually added: fs.inotify.max_user_watches=524288

Everything seems to be fine except to watch the folder which can be a pain if I have to re-build all the time.  I do appreciate this is a little too specific on the environment and might not be anything for me to do.

Cheers,

Stu

**Comment by phated** [comment]
There must be problems with the permissions (EPERM) when attempting to watch a file in Bash on Windows.  I have no experience with this.  I'll label it as "help wanted" and "further investigation required".

**Comment by darthvader666uk** [comment]
Thanks for this.  Hopefully someone can help me figure out whats going on :/

**Comment by emilekberg** [comment]
This is an issue with bash, i think it's fixed in the developer version, but not in the live one yet. https://github.com/Microsoft/BashOnWindows/issues/216

**Comment by darthvader666uk** [comment]
Thanks for the Link, Hopefully the MS fix will be in place soon!

**Comment by callumacrae** [comment]
@darthvader666uk Would you be able to test whether this issue still occurs with the developer version?

I think it would be a good idea to leave this issue open for visibility until it's fixed on the live version anyway.

**Comment by darthvader666uk** [comment]
@callumacrae I shall update to developer version now and see if it is still happening there

**Comment by phated** [comment]
I'm going to close this, as it was a Bash on Windows problem.  Even though I don't think it is generally available yet, people running into this can install the developer version.

**Comment by udeshrl** [comment]
I am still facing this issue on Window Bash, is there any solution for it??

**Comment by darthvader666uk** [comment]
@phated I tried to install the Windows Developer version but kept failing and had to nuke the windows install 3 times.  Kind of gave up in the end.  Maybe tis due to the version of Windows 10 I have (home).  I think im going to have to wait for an update :/
