### ISSUE TITLE
events.js:160    throw er; // Unhandled 'error' event 

### ISSUE THREAD

**Issue by brandonpowell** [gulpjs/gulp#1886]
When every I type gulp into my command lines I get this message in Terminal that says: I have never ran by this error message before can some help me, please.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

```
SyntaxError: Unexpected token / in JSON at position 668
    at Object.parse (native)
    at /Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/lib/detect-dependencies.js:70:36
    at Array.forEach (native)
    at findComponentConfigFile (/Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/lib/detect-dependencies.js:66:5)
    at /Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/lib/detect-dependencies.js:145:31
    at /Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/node_modules/lodash/lodash.js:3001:24)
    at /Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/Users/brandonpowell/sites/valet/wordpress-development/web/app/themes/alegacyleftbehind/node_modules/wiredep/lib/detect-dependencies.js:34:7)
```
```

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
