### ISSUE TITLE
when npm install --save-dev gulp, npm ERR! Darwin 16.4.0

### ISSUE THREAD

**Issue by asnil** [gulpjs/gulp#1917]
I'm using npm install gulp in devDependencies, When I run `npm install --save-dev gulp` after `npm init`, some error on the terminal
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/myname/.nvm/versions/node/v6.10.0/bin/node" "/Users/myname/.nvm/versions/node/v6.10.0/bin/npm" "install" "--save-dev" "gulp"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF
npm ERR! Refusing to install gulp as a dependency of itself
```

the package.json:
```
{
  "name": "gulp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/myname/.nvm/versions/node/v6.10.0/bin/node',
1 verbose cli   '/Users/myname/.nvm/versions/node/v6.10.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp',
12 silly mapToRegistry   name: 'gulp',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/gulp
14 verbose request uri https://registry.npmjs.org/gulp
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:22:38
17 verbose request id cff0f8b6bc243e6c
18 verbose etag W/"58ad4b9a-1ce32"
19 verbose lastModified Wed, 22 Feb 2017 08:28:10 GMT
20 http request GET https://registry.npmjs.org/gulp
21 http 304 https://registry.npmjs.org/gulp
22 verbose headers { date: 'Fri, 24 Feb 2017 02:22:38 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58ad4b9a-1ce32"',
22 verbose headers   age: '270',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-nrt6131-NRT',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '7',
22 verbose headers   'x-timer': 'S1487902958.991443,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 24 Feb 2017 02:22:38 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58ad4b9a-1ce32"',
23 silly get     age: '270',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-nrt6131-NRT',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '7',
23 silly get     'x-timer': 'S1487902958.991443,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/gulp from cache
25 verbose get saving gulp to /Users/myname/.npm/registry.npmjs.org/gulp/.cache.json
26 verbose correctMkdir /Users/myname/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install gulp as a dependency of itself
43 verbose stack     at checkSelf (/Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/Users/myname/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/myname/web/gulp
45 error Darwin 16.4.0
46 error argv "/Users/myname/.nvm/versions/node/v6.10.0/bin/node" "/Users/myname/.nvm/versions/node/v6.10.0/bin/npm" "install" "--save-dev" "gulp"
47 error node v6.10.0
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install gulp as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
```

**Comment by asnil** [comment]
npm install --save-dev gulp

**Comment by phated** [comment]
Don't name your project gulp...
