### ISSUE TITLE
Gulp is broken in v7.7.4

### ISSUE THREAD

**Issue by JoshuaWise** [gulpjs/gulp#1931]
I ran a node script that had only one line:
```js
var gulp = require('gulp');
```

**What were you expecting to happen?**

For it to not crash

**What actually happened?**

It crashed with:
```
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/project/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

(posted above)

**What version of gulp are you using?**

`3.9.1`

**What versions of npm and node are you using?**

```bash
$ node -v
v7.7.4
```

**Comment by contra** [comment]
Can you try running npm update and `npm rebuild`?

**Comment by phated** [comment]
3.x doesn't work in node 7. Don't use unstable versions of node.

**Comment by teohhanhui** [comment]
node 7 has been officially released since last October. It's not a LTS release, but not "unstable".
