### ISSUE TITLE
Reading files from the standard input, returning them to the standard output with gulp4

### ISSUE THREAD

**Issue by DJviolin** [gulpjs/gulp#1947]
I have a shell script which recursively reading html files:

```bash
#!/bin/bash

set -e

/usr/bin/find ./static -name '*.html' -type f -print0 |
    while IFS= read -r -d $'\0' line; do
        echo "$line"
        node --use_strict ./minify.js -f "$line" -t html > "$line.bak"
    done
```

I calling `/usr/bin/find`, because this way not interfere with the Windows `find` command in `mingw64`

In my js file, I reading the arguments with `minimist` and trying to feed these files to gulp, process it (html, css, js minification) and print the results to standard output.

```js
'use strict';

const argv = require('minimist')(process.argv.slice(2));
const gulp = require('gulp');
const htmlmin = require('gulp-htmlmin');

if (argv['f'] !== undefined) {
} else {
  process.exitCode = 1;
  process.exit();
}

gulp.task('htmlmin', () =>
  gulp.src(argv['f'])
    .pipe(htmlmin({collapseWhitespace: true}))
    //.pipe(gulp.dest(process.stdout.write()))
);

if (argv['t'] === 'html') {
  gulp.series('htmlmin')();
} else {
  process.exitCode = 1;
  process.exit();
}
```

This doesn't work and even if I just only including the `const gulp = require('gulp');` in the head (just a plain file with this ony line), always throwing this error:

```bash
Sink.prototype._write = function(_, _, cb) {
                                    ^
SyntaxError: Duplicate parameter name not allowed in this context
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xampp\htdocs\public_html\mysite\node_modules\async-done\index.js:8:15)
    at Module._compile (module.js:570:32)
```

Tested Node.js versions: v6.9.5 and v7.9.0

**Comment by DJviolin** [comment]
Error caused by `__use_strict`.

**Comment by phated** [comment]
That flag is extremely dangerous and doesn't do what most people think.  I wish they'd just remove it...
