### ISSUE TITLE
Error: Cannot find module 'has-flag'

### ISSUE THREAD

**Issue by markorapaic** [gulpjs/gulp#1976]
Hello - i've recently upgraded my node and npm versions via homebrew to `8.1.2` and `5.0.3`.

I've had issues with Gulp tonight, so I thought i'd uninstall it and reinstall it to see how that goes. Sadly its not going well, here is my terminal output. I'm on a mac running El Capitan.

You can see below that everything uninstalls and reinstalls without an error, and both my global and local versions are the same (and recent).

```
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ npm uninstall gulp
removed 85 packages in 5.691s
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ npm uninstall -g gulp
removed 199 packages in 3.718s
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ npm install -g gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/Users/mysteryuser/.npm-packages/bin/gulp -> /Users/mysteryuser/.npm-packages/lib/node_modules/gulp/bin/gulp.js
+ gulp@3.9.1
added 186 packages in 7.851s
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ npm install gulp
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
+ gulp@3.9.1
added 78 packages in 7.928s
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ gulp -v
[23:44:15] CLI version 3.9.1
[23:44:15] Local version 3.9.1
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ gulp
module.js:487
    throw err;
    ^

Error: Cannot find module 'has-flag'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/www/mystery-website/site/web/app/themes/mystery-theme/node_modules/postcss/node_modules/supports-color/index.js:2:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
mysteryuser@mysteryusersimac:/www/mystery-website/site/web/app/themes/mystery-theme$ 
```

**Comment by doowb** [comment]
> at Object.<anonymous> (/www/mystery-website/site/web/app/themes/mystery-theme/node_modules/postcss/node_modules/supports-color/index.js:2:15)

This isn't a gulp issue. This is probably an issue with npm. Delete the local node_modules folder in your project and re-install your dependencies.

**Comment by phated** [comment]
^ @doowb is correct.
