### ISSUE TITLE
Error: Unbalanced delimiter found in string

### ISSUE THREAD

**Issue by karthinuk107** [gulpjs/gulp#2004]
Here's the Issue I am getting when I am using 'npm run dev'

[12:54:21] Finished 'generateSpritesheet' after 21 ms
Spritesheet _sprite file written...
[12:54:21] 'markup' errored after 175 ms
[12:54:21] Error: Unbalanced delimiter found in string
    at Function.XRegExp.matchRecursive (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/preprocess/node_modules/xregexp/src/addons/matchrecursive.js:176:23)
    at matchReplacePass (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/preprocess/lib/preprocess.js:291:27)
    at replaceRecursive (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/preprocess/lib/preprocess.js:321:10)
    at preprocessor (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/preprocess/lib/preprocess.js:164:10)
    at Object.preprocess (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/preprocess/lib/preprocess.js:89:10)
    at ppStream (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/gulp-preprocess/index.js:24:19)
    at wrappedMapper (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/map-stream/index.js:96:21)
    at DestroyableTransform.ondata (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
    at addChunk (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at afterTransform (/Users/kvincent1/Desktop/fact-checker/gulp-frontend-boilerplate/node_modules/readable-stream/lib/_stream_transform.js:102:51)
[12:54:21] 'default' errored after 178 ms
[12:54:21] The following tasks did not complete: images, optimizeImages, generateFavicons
[12:54:21] Did you forget to signal async completion?

**Comment by phated** [comment]
This is not a gulp problem.  Please review your stack trace to see where your error is being generated.
