### ISSUE TITLE
Error Running gulp build

### ISSUE THREAD

**Issue by hemanthaSN** [gulpjs/gulp#2017]
Before the gulp build command, I have executed below commands
npm install --global gulp-cli
npm install gulp
npm install --unsafe-perm 
then gulp build 

**What were you expecting to happen?**
gulp build should build without any error.

**What actually happened?**
   after executing the gulp build command, am getting below error
   [09:04:01] Finished 'assets' after 897 ms
[09:04:01] Finished 'icons' after 976 ms

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./src/app/frontend/index_module.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/tmp/dashboard-1.6.2/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (/tmp/dashboard-1.6.2/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (/tmp/dashboard-1.6.2/node_modules/babel-loader/lib/index.js:113:132)

**What version of gulp are you using?**
  am using 3.9.1, 

**What versions of npm and node are you using?**
  npm-3.10.10

**Comment by phated** [comment]
Look at your stack trace, this is isn't a gulp problem. It's in babel-loader.
