### ISSUE TITLE
log4js Error

### ISSUE THREAD

**Issue by VidyEmer** [gulpjs/gulp#2036]
/home/bot/node_modules/log4js/lib/configuration.js:42
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:42:15)
    at Array.forEach (<anonymous>)
    at Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:40:11)
    at new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:203:10)
    at Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:201:12)
    at Object.<anonymous> (/home/bot/site.js:10:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)

Anybody have a fix for this?

**Comment by phated** [comment]
This is not a support forum. Support questions should be directed to StackOverflow.
