### ISSUE TITLE
Local gulp cannot found

### ISSUE THREAD

**Issue by erkort** [gulpjs/gulp#2047]
there is a problem that I cannot solve in gulpfile.js. It seems correct on my pc (gulp bower -g) but whenever I run gulp, It shows me a local gulp cannot found an error. If I reinstall it local but this time it doesn't find any modules. this time I reinstall every module step by step but it gives me another error. I cannot solve it. what is the problem? also, I verified NODE_PATH and I cannot get anything. Need some help  

C:\Users\Mert\Desktop\erkutDion\dion>npm -v
5.5.1

C:\Users\Mert\Desktop\erkutDion\dion>node -v
v8.9.1

C:\Users\Mert\Desktop\erkutDion\dion>bower -v
1.8.2

C:\Users\Mert\Desktop\erkutDion\dion>gulp -v
[15:35:19] CLI version 1.4.0

C:\Users\Mert\Desktop\erkutDion\dion>gulp
[15:35:26] Local gulp not found in ~\Desktop\erkutDion\dion
[15:35:26] Try running: npm install gulp

C:\Users\Mert\Desktop\erkutDion\dion>npm install npm
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN dion@1.0.0 No repository field.

+ npm@5.5.1
added 460 packages in 85.849s

C:\Users\Mert\Desktop\erkutDion\dion>npm install bower
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN dion@1.0.0 No repository field.

+ bower@1.8.2
added 1 package in 23.224s

C:\Users\Mert\Desktop\erkutDion\dion>gulp
[15:39:36] Local gulp not found in ~\Desktop\erkutDion\dion
[15:39:36] Try running: npm install gulp

C:\Users\Mert\Desktop\erkutDion\dion>npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN dion@1.0.0 No repository field.

+ gulp@3.9.1
added 186 packages in 30.758s

C:\Users\Mert\Desktop\erkutDion\dion>gulp
module.js:538
    throw err;
    ^

Error: Cannot find module 'gulp-watch'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mert\Desktop\erkutDion\dion\gulpfile.js:4:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

C:\Users\Mert\Desktop\erkutDion\dion>npm install gulp-watch
npm WARN dion@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ gulp-watch@4.3.11
added 153 packages in 31.582s

C:\Users\Mert\Desktop\erkutDion\dion>gulp
module.js:538
    throw err;
    ^

Error: Cannot find module 'gulp-autoprefixer'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mert\Desktop\erkutDion\dion\gulpfile.js:5:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

C:\Users\Mert\Desktop\erkutDion\dion>

**Comment by phated** [comment]
You seem to be requiring modules that you haven't installed. Future support questions should be directed to StackOverflow.
