### ISSUE TITLE
Gulp: TypeError: Cannot read property 'task' of undefined

### ISSUE THREAD

**Issue by ScottAgirs** [gulpjs/gulp#2050]
Greetings, 

A first-time Gulp user here.
Just set everything up according to [this guide](https://code.tutsplus.com/tutorials/using-gulp-for-wordpress-automation--cms-23081) and I'm getting the  following error, when running `gulp`  :

```
TypeError: Cannot read property 'task' of undefined
    at Object.<anonymous> (/Users/myUserName/workspace/wp-sites/myProject/wp-content/themes/wp-gulp-automation/gulpfile.js:9:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
myLaptop:wp-gulp-automation myUserName$
```

My gulpfile.js:
```
var sass = require('gulp-sass');
var jshint = require('gulp-jshint');
var concat = require('gulp-concat');
var imagemin = require('gulp-imagemin');
var plumber = require('gulp-plumber');
var notify = require('gulp-notify');

// Adding SASS Compilation
gulp.task('sass', function () {

    gulp.src('./css/src/*.scss')

        .pipe(plumber(plumberErrorHandler))

        .pipe(sass())

        .pipe(gulp.dest('./css'))

});

// Adding JS Compilation
gulp.task('js', function () {

    gulp.src('js/src/*.js')

        .pipe(plumber(plumberErrorHandler))

        .pipe(jshint())

        .pipe(jshint.reporter('fail'))

        .pipe(concat('theme.js'))

        .pipe(gulp.dest('js'));

});

// Image optimization

gulp.task('img', function() {

      gulp.src('img/src/*.{png,jpg,gif}')

          .pipe(plumber(plumberErrorHandler))
          
          .pipe(imagemin({

            optimizationLevel: 7,

            progressive: true

          }))

          .pipe(gulp.dest('img'))

});


// SYSTEM //


// Watch files being edited

gulp.task('watch', function() {

  gulp.watch('css/src/*.scss', ['sass']);

  gulp.watch('js/src/*.js', ['js']);

  gulp.watch('img/src/*.{png,jpg,gif}', ['img']);

});


// Show error messages
var plumberErrorHandler = { errorHandler: notify.onError({

    title: 'Gulp',

    message: 'Error: <%= error.message %>'

  })

};

// Default GULP actions

gulp.task(['sass'], ['js'], ['img'], ['watch']);

var gulp = require('gulp');

gulp.task('default', function(){

    console.log('default gulp task...')

});

```

**Comment by phated** [comment]
You can't require gulp at the bottom of the file but use it above.  That's not how JS works.  Please direct future support questions to StackOverflow, as this tracker is only for issues.
