### ISSUE TITLE
gulp@4.0.0-alpha.3 breaks Pumpify with issue "premature close"

### ISSUE THREAD

**Issue by avdeev** [gulpjs/gulp#2074]
**gulpfile.js**
```js
const jstConcat = require('gulp-jst-concat');

gulp.task('jst', () =>
  gulp.src(paths.JST_SOURCE)
    .pipe(jstConcat('jst.js', {
      renameKeys: ['^.*templates/(.*).html$', '$1']
    }))
    .pipe(gulp.dest('static'))
);
```

**CLI**
```shell
[16:48:47] Using gulpfile ~/projects/xxx/gulpfile.js
[16:48:47] Starting 'jst'...
[16:48:47] 'jst' errored after 82 ms
[16:48:47] Error: premature close
    at Pumpify.onclose (/Users/alexeyavdeev/projects/xxx/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:106:13)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/Users/alexeyavdeev/projects/xxx/node_modules/duplexify/index.js:192:8)
    at /Users/alexeyavdeev/projects/xxx/node_modules/duplexify/index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by phated** [comment]
You are using an insanely (4 years!!!) out-of-date plugin that is using the now-deprecated gulp-util and the `through` module that doesn't support new streams (we've been suggesting `through2` for years).

**Comment by eliasmamo** [comment]
@phated  Well for me it fails if i have RevAll.manifestFile() line, I've checked inside it uses through2 but this task:
```
function addRevision() {
  return gulp
    .src(['./build/unbundled/**', '!./build/unbundled/bower_components/**/*'])
    .pipe(RevAll.revision({))
    .pipe(gulp.dest('./build/temp'))
    .pipe(RevAll.manifestFile())
    .pipe(gulp.dest('./build/temp'));
}
```
fails with
```
[11:20:01] Error: premature close
    at Pumpify.onclose (/home/ZZZ/main/app/node_modules/end-of-stream/index.js:43:67)
    at emitNone (events.js:106:13)
    at Pumpify.emit (events.js:208:7)
    at Pumpify.Duplexify._destroy (/home/ZZZ/main/app/node_modules/duplexify/index.js:192:8)
    at /home/ZZZ/main/app/node_modules/duplexify/index.js:175:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by avdeev** [comment]
@eliasmamo Try to remove gulp-util from RevAll

**Comment by phated** [comment]
@eliasmamo based on your hacked up example, I don't think you are showing everything in that pipeline.  gulp-rev-all would be failing for using the `gutil.File` API but not with premature close.
