### ISSUE TITLE
Task declaration order

### ISSUE THREAD

**Issue by ryuran** [gulpjs/gulp#2087]
**What were you expecting to happen?**
1. I have my task dispatched in several files
2. I load all task files from the `task` directory (see files below)
4. `gulp all` should run without error

**What actually happened?**
```
assert.js:42
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: Task never defined: task1
    at getFunction (./node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at map (/Users/yliechti/Sites/trygsknext/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (./node_modules/undertaker/lib/helpers/normalizeArgs.js:22:10)
    at Gulp.series (/Users/yliechti/Sites/trygsknext/node_modules/undertaker/lib/series.js:13:14)
    at Object.<anonymous> (./task/all.js:3:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Because files are loaded in alphabetic order and `all.js` try to resolve the `task1` task before assignation.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
`gulpfile.js`: 
```javascript
require('task');
```

`task/index.js`
```javascript
const path = require('path');

require('fs').readdirSync(path.relative(process.cwd() , __dirname)).forEach(function(file) {
  require(path.resolve(__dirname, file));
});
```

File`task/task1.js`:
```javascript
const gulp = require('gulp');

gulp.task('task1', function() {
  console.log('task1');
});
```

File`task/all.js`:
```javascript
const gulp = require('gulp');

gulp.task('all', gulp.series('task1', function(){
  console.log('it should work');
}));
```

**What version of gulp are you using?**
`4.0.0`
This method was working with gulp 3

**What versions of npm and node are you using?**
node: v8.9.1
npm: v5.5.1

**Comment by ryuran** [comment]
I think it's related to #802

**Comment by ryuran** [comment]
I resolve it declaring interdependances of task by `require(…);`

**Comment by phated** [comment]
@ryuran this is a design decision - "load all" isn't a good pattern. Glad you solved it.
