### ISSUE TITLE
Gulp 4 Alpha 3 Error: using browserify leads to "already started" error

### ISSUE THREAD

**Issue by Dan503** [gulpjs/gulp#2090]
I've been using Gulp 4 for a while now and loving it. Not long ago Gulp 4 Alpha 3 was released.

Since Alpha 3 was released, I haven't been able to compile any of my sites with it.

My sites essentially use the Gulp [browserify+watchify recipe]( https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md) for handling JS and that seems to be where the code is breaking.

It started off with `Error: Received a non-Vinyl object in dest()` but that was just because I needed to update "vinyl-source-stream" to the latest version.

After updating "vinyl-source-stream" to v2.0.0 I ran into another error `Error: already started`. I haven't been able to figure that one out yet.

Here is the full call stack error:

`````````````
C:\xxxxxxx\node_modules\cloneable-readable\index.js:38
    throw new Error('already started')
    ^


Error: already started
    at Cloneable.clone (C:\xxxxxxx\node_modules\cloneable-readable\index.js:38:11)
    at File.clone (C:\xxxxxxx\node_modules\vinyl-source-stream\node_modules\vinyl\index.js:117:30)
    at BufferList._callback (C:\xxxxxxx\node_modules\vinyl-buffer\index.js:18:19)
    at BufferList.end (C:\xxxxxxx\node_modules\vinyl-buffer\node_modules\bl\bl.js:83:10)
    at Cloneable.onend (C:\xxxxxxx\node_modules\readable-stream\lib\_stream_readable.js:570:10)
    at Cloneable.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Cloneable.emit (events.js:185:7)
    at endReadableNT (C:\xxxxxxx\node_modules\readable-stream\lib\_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
`````````````

I'm not sure who is actually to blame for the error. It could be Gulp, browserify, or vinyl-source-stream. It's not watchify. I disbled watchify and the error still occurred.

Any help would be appreciated :)

**Comment by phated** [comment]
Hey @Dan503! You need to update vinyl-buffer to version 1.0.1 also - there was a bug in it that had gone unnoticed.  You might have it locked in a package-lock.json file so it might have not installed, even though we've used proper semver.

**Comment by Dan503** [comment]
Thanks! Updating vinyl-buffer worked :)
