### ISSUE TITLE
Gulp 4 alpha 3 Error: TypeError: file.pipe is not a function

### ISSUE THREAD

**Issue by Dan503** [gulpjs/gulp#2091]
Another broken gulp plugin that isn't being maintained any more (hasn't been updated for 2 years) :(

https://github.com/gtg092x/gulp-sftp/issues/78

Full stack trace:

``````
[18:17:12] TypeError: file.pipe is not a function
    at C:\xxxxxx\prototype\node_modules\gulp-sftp\index.js:275:22
    at Object.async.whilst (C:\xxxxxx\prototype\node_modules\gulp-sftp\node_modules\async\lib\async.js:683:13)
    at C:\xxxxxx\prototype\node_modules\gulp-sftp\node_modules\async\lib\async.js:679:23
    at C:\xxxxxx\prototype\node_modules\gulp-sftp\index.js:255:21
    at SFTP._parse (C:\xxxxxx\prototype\node_modules\ssh2\lib\SFTP\SFTPv3.js:1093:13)
    at ChannelStream.<anonymous> (C:\xxxxxx\prototype\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at emitOne (events.js:96:13)
    at ChannelStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ChannelStream.Readable.push (_stream_readable.js:134:10)
``````

I know that it's not really your responsibility but I'm hoping that your Gulp expertise will know what needs to change in the gulp-sftp plugin for it to start working again.

This plugin worked fine with Gulp 4 Alpha 2. It broke when Alpha 3 was released.

**Comment by phated** [comment]
@Dan503 Sorry you are using an insanely unmaintained plugin (P.S. - I'd avoid these things) but we removed the `pipe` method that existed on a Vinyl object because the API was very bad and did not do what people expected.  Plugins now need to be handling null/streaming/buffer contents specifically instead of that opaque `file.pipe` API

**Comment by Dan503** [comment]
Thanks for the input :)
