### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ankurkaush** [gulpjs/gulp#2110]
return transactions.length > 0;
                               ^

TypeError: Cannot read property 'length' of undefined
    at E:\ankur\try2\node_modules\iota.lib.js\lib\api\api.js:882:32
    at next (E:\ankur\try2\node_modules\async\dist\async.js:3007:18)
    at E:\ankur\try2\node_modules\iota.lib.js\lib\api\api.js:868:17
    at makeRequest.prepareResult (E:\ankur\try2\node_modules\iota.lib.js\lib\utils\makeRequest.js:313:12)
    at exports.XMLHttpRequest.request.onreadystatechange (E:\ankur\try2\node_modules\iota.lib.js\lib\utils\makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (E:\ankur\try2\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (E:\ankur\try2\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (E:\ankur\try2\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)

**Comment by demurgos** [comment]
This issue is not related to Gulp. Read the stack trace: it is related to some library called `iota.lib.js`.

**Comment by phated** [comment]
^

**Comment by ankurkaush** [comment]
why close my post sir

**Comment by demurgos** [comment]
@ankurkaush 
I replied to you: this issue is not related to Gulp. Open an issue on `iota.lib.js`.

If you believe that it is really caused by Gulp, [use the issue template](https://raw.githubusercontent.com/gulpjs/gulp/master/.github/ISSUE_TEMPLATE.md) and properly explain your situation instead of just dumping a stack trace.

**Comment by ankurkaush** [comment]
why close my post sir
