### ISSUE TITLE
Cannot read property 'on' of undefined  when a task belong to a series task group

### ISSUE THREAD

**Issue by scil** [gulpjs/gulp#2141]
Two tasks and group them using  gulp.series

```js
var gulp = require('gulp');
var del = require('del');
var sourcemaps = require('gulp-sourcemaps');
var sass = require('gulp-sass');


function clean() {
    return del([
        'public/css/app.css',
    ]);
}

function sass_ferry() {    
    returnn  gulp.src('./resources/assets/sass/ferry.scss')
        .pipe(sourcemaps.init())
        .pipe(sass())
        .pipe(sourcemaps.write('../../../public/css/map', {addComment: false}))
        .pipe(gulp.dest('./resources/views/css'));
}

// group theses two tasks
var sass = gulp.series(clean, sass_ferry);  

exports.sass_ferry = sass_ferry;
exports.sass = sass;


```

run `gulp sass_ferry`, and I found that task `clean`  also start
```
[16:39:58] Using gulpfile /vagrant/www/zc/gulpfile.js
[16:39:58] Starting 'sass_ferry'...
[16:39:58] Starting 'clean'...
[16:39:58] 'sass_ferry' errored after 22 ms
[16:39:58] TypeError: Cannot read property 'on' of undefined
    at sass_ferry (/vagrant/www/zc/gulpfile.js:261:92)
    at taskWrapper (/vagrant/www/zc/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/vagrant/www/zc/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[16:39:58] The following tasks did not complete: clean
[16:39:58] Did you forget to signal async completion?
```

If I del `var sass = gulp.series(clean, sass_ferry);  `,  this error disappear.  
It seamed that task sass_ferry and clean are binded together.

**What version of gulp are you using?**
4.0

**What versions of npm and node are you using?**
8.10.0 
5.6.0

**Comment by phated** [comment]
This is not a support forum. Please direct support questions to StackOverflow.
