### ISSUE TITLE
Failed to load external module babel-register

### ISSUE THREAD

**Issue by rupesh2017** [gulpjs/gulp#2145]
running Ubuntu 17.10
node -v
v9.11.1
npm -v
5.8.0

 **npm start**

> victor-hugo@1.0.0 start /home/greenseek/Desktop/hugo-restaurant-tutorial
> gulp server

[15:53:54] Failed to load external module @babel/register
[15:53:54] Requiring external module babel-register
[15:53:54] Using gulpfile /home/greenseek/Desktop/hugo-restaurant-tutorial/gulpfile.babel.js

tried
1)npm i -S babel-register 
not working
2)
npm cache clean
npm uninstall -g gulp, open a new Terminal tab, npm install -g gulp

not working

3)npm install --save-dev babel-preset-es2015
not working

4)npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

5)npm install babel-core --save-dev

6)npm install babel --save-dev

all same issue?

**Comment by demurgos** [comment]
Could you post a link to the repo with the issue? Or create a [Gist](https://gist.github.com/) reproducing the issue?

What is your gulp version (`gulp --version`)? Try to install `npm install -g gulp-cli@2` and `npm install gulp@4`.

**Comment by rupesh2017** [comment]
gulp -v
CLI version 3.9.1

https://github.com/rupesh2017/hugo-restaurant-tutorial

**npm install gulp@4**

npm WARN react-toolbox@1.3.4 requires a peer of react@^0.14 || ~15.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.3.4 requires a peer of react-addons-css-transition-group@^0.14.0 || ~15.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-toolbox@1.3.4 requires a peer of react-dom@^0.14.0 || ~15.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN victor-hugo@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})



**npm start**

Failed to load external module @babel/register

still persist 

now when i checked **gulp -v**
CLI version 2.0.1

**Comment by rupesh2017** [comment]
I don't what i did but now
victor-hugo@1.0.0 start /home/greenseek/Desktop/hugo-restaurant-tutorial
> gulp server

[20:59:02] Failed to load external module @babel/register
[20:59:02] Requiring external module babel-register
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/gulpfile.babel.js:22:6)
    at Module._compile (module.js:652:30)
    at loader (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:195:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
