### ISSUE TITLE
help wanted to resolve the error 

### ISSUE THREAD

**Issue by rupesh2017** [gulpjs/gulp#2148]
gulp server

[16:52:54] Failed to load external module @babel/register
[16:52:54] Requiring external module babel-register
assert.js:49
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/gulpfile.babel.js:22:6)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at loader (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:195:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-10T11_23_10_799Z-debug.log
root@greenseek-Vostro-14-5459:/home/greenseek/Desktop/hugo-restaurant-tutorial# ^C
root@greenseek-Vostro-14-5459:/home/greenseek/Desktop/hugo-restaurant-tutorial# assert.js:49
assert.js:49: command not found
root@greenseek-Vostro-14-5459:/home/greenseek/Desktop/hugo-restaurant-tutorial#   throw new AssertionError(obj);
bash: syntax error near unexpected token `('

**Comment by rupesh2017** [comment]
I didn't wrote those function 
**npm start** command generated this error.

**Comment by doowb** [comment]
You should ask the person that wrote the `hugo-restaurant-tutorial` or ask on StackOverflow.
