### ISSUE TITLE
task fail when there is warning not an error

### ISSUE THREAD

**Issue by sandangel** [gulpjs/gulp#2149]
**What were you expecting to happen?**
Warning should not make the task fail

**What actually happened?**
```sh
HeadlessChrome 67.0.3372 (Mac OS X 10.13.4): Executed 42 of 42 SUCCESS (0.301 secs / 0 secs)
[00:03:48] '<anonymous>' errored after 9.03 s
[00:03:48] Error: (node:62013) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

    at formatError (/Users/sand/Downloads/ng6/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
    at Gulp.<anonymous> (/Users/sand/Downloads/ng6/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Object.error (/Users/sand/Downloads/ng6/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/sand/Downloads/ng6/node_modules/now-and-later/lib/map.js:46:14)
```
**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

```js
gulp.task(function () {
	/* execute binary `ng test`*/
});
```

**What version of gulp are you using?** 4.0.0

**What versions of npm and node are you using?** node 8.11.1, yarn 1.5.1

**Comment by doowb** [comment]
If something is throwing an error inside the task, then gulp will fail. You should open an issue with whatever the `Tapable.plugin` thing is or make sure you're doing the ``/* execute binary `ng test`*/``  correctly.

**Comment by sandangel** [comment]
Hi, @doowb I have run the binary manually (ng test for angular repo) and it just a warning as described like above and the command has gracefully terminated with exit code 0. But when I wrap that command into the gulp task, it seems like gulp parse error does not realize that this is a warning and the task has fail. Could you please review the issue?

**Comment by doowb** [comment]
I'm pretty sure this is not a gulp issue, but is an issue with how you wrap the command. If you show how that is done, someone might be able to help.

**Comment by sandangel** [comment]
@doowb thank you for confirm. I will investigate the issue.
