### ISSUE TITLE
Gulp doesn't run "gulpInst.start.apply(gulpInst, toRun); cannot read property"

### ISSUE THREAD

**Issue by ajCastiglione** [gulpjs/gulp#2169]
**What were you expecting to happen?**
I tried to run the command "gulp" as i've done for the past couple months and had this randomly break.
Not sure what causes this issue but if I run the command (node ./node_modules/gulp/bin/gulp.js) it will run my gulp file but it won't run correctly. Browser sync won't reload the web page and some things don't compile correctly. 

Link to repo: https://github.com/ajCastiglione/movie-query-api
 
**What actually happened?**
[20:46:11] Using gulpfile ~\Documents\Projects\movie-api\gulpfile.js
C:\Users\Owner\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Owner\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
const gulp = require('gulp');
const sass = require('gulp-sass');
const autoprefixer = require('gulp-autoprefixer');
const browserSync = require('browser-sync').create();

gulp.task('default', function() {
  gulp.watch('scss/**/*.scss', gulp.series('styles'));
});

gulp.task('styles', function() {
  return gulp.src('scss/*.scss')
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(autoprefixer({
      browsers: ['last 2 versions']
    }))
    .pipe(gulp.dest('./css'))
    .pipe(browserSync.stream({match: 'index.html, css/*.css, js/*.js'}));
});

browserSync.init({
  injectChanges: true,
  files: ['index.html', 'css/*.css', 'js/*.js'],
  server: "./"
});
browserSync.stream();

**What version of gulp are you using?**
4.0.0
**What versions of npm and node are you using?**
NPM - 5.6.0
Node - 8.11.1

**Comment by ajCastiglione** [comment]
Well then im at a loss then because it only fails on windows. At work I use a mac and have the exact same repo. Running gulp on the mac works as intended but on windows it errors out saying its undefined.

**Comment by ajCastiglione** [comment]
Can you elaborate instead of telling me that the cli version is incorrect? As i expressed in a previous comment, same repo on both mac and windows yet mac works while windows errors out.

**Comment by phated** [comment]
No. Read the article.
