### ISSUE TITLE
gulp watch error (ENOSPC)

### ISSUE THREAD

**Issue by escapedcat** [gulpjs/gulp#217]
Since today my watch task is broken.
That's what I get:

```
gulp watch
[gulp] Using file /var/www/project/gulpfile.js
[gulp] Working directory changed to /var/www/project
[gulp] Running 'watch'...
[gulp] Errored 'watch' in 10 ms watch ENOSPC

/var/www/project/node_modules/gulp/node_modules/orchestrator/index.js:153
            throw err;
                  ^
Error: watch ENOSPC
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Gaze._watchDir (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:279:30)
    at /var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:336:10
    at iterate (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:332:10)
    at Gaze.add (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:167:8)
    at new Gaze (/var/www/project/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:68:10)
```

My gulpfile.js:

```
var gulp        = require('gulp');

// Watch
gulp.task('watch', function() {
    // Watch .scss files
    gulp.watch('app/sass/**/*.scss', function(event) {
        //console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });
});

```

My package.js:

```
{
  "name": "project",
  "version": "0.0.1",
  "dependencies": {
  },
  "devDependencies": {
    "gulp": "*",
    "gulp-ruby-sass": "*",
    "gulp-minify-css": "*",
    "gulp-jshint": "*",
    "gulp-concat": "*",
    "gulp-uglify": "*",
    "gulp-imagemin": "*",
    "gulp-clean": "*",
    "gulp-cache": "*",
    "gulp-notify": "*",
    "gulp-web-modules": "*",
    "gulp-serve": "*",
    "gulp-plumber": "*",
    "jshint-stylish": "*"
  }
}
```

Not sure if I somehow broke something... but it was working before :P

**Comment by mzahor** [comment]
@cancerberoSgx thanks, it works.

**Comment by heshzad** [comment]
Thanks @cancerberoSgx . it's work.

**Comment by Asher-Tan** [comment]
thanks ! @cancerberoSgx

**Comment by Sofyi** [comment]
@cancerberoSgx Thanks man! it works!

**Comment by selahattinunlu** [comment]
@cancerberoSgx Thanks!

**Comment by racerboy** [comment]
@cancerberoSgx Great! How did you know that? Thanks!

**Comment by rlucha** [comment]
@cancerberoSgx thank you :)

**Comment by ibrahimelbanna** [comment]
@cancerberoSgx Thanks man! it works!

**Comment by callumacrae** [comment]
@contra please could you lock this? Too much noise :(
