### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by MetaiR** [gulpjs/gulp#2236]
i couldn't install gulp using `npm i gulp -g`

it seems that one of the dependency's link has been removed and the installation failing on downloading

this is my log:

```sh
Seyed@MetaiR MINGW64 /h/git
$ npm i glup -g
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated bower-files@3.14.1: This module is no longer being maintained. Please reach out to package author if you wish to take over maintenance. For alternatives, use wiredep, or migrate to something like webpack
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> node-sass@3.13.1 install C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> phantomjs-prebuilt@2.1.16 install C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\phantomjs-prebuilt
> node install.js

(node:9372) ExperimentalWarning: The fs.promises API is experimental
PhantomJS not found on PATH
Download already available at C:\Users\Seyed\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\Seyed\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1539294444504\phantomjs-2.1.1-windows -> C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> node-sass@3.13.1 postinstall C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:165:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Seyed\\AppData\\Roaming\\npm\\node_modules\\glup\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Seyed\AppData\Roaming\npm\node_modules\glup\node_modules\node-sass
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\glup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Seyed\AppData\Roaming\npm-cache\_logs\2018-10-11T21_47_30_070Z-debug.log
```

**Comment by phated** [comment]
node-sass has nothing to do with us, nor does your (hopefully typo'd) `glup` library.
