### ISSUE TITLE
internal/modules/cjs/loader.js:605     throw err;     ^  Error: Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by dimative** [gulpjs/gulp#2284]
# gulp --version
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

Hello. 
node -v - v11.6.0
npm -v 6.5.0-next.0.
Ubuntu 18.04 please help me fix it.

**Comment by paulomp90** [comment]
@dimative were you able to overcome this error?
