### ISSUE TITLE
Gulp not working saying missing module 

### ISSUE THREAD

**Issue by BigWizzo** [gulpjs/gulp#2286]
Hie. I have installed gulp as per [https://gulpjs.com/docs/en/getting-started/quick-start](url) When I run gulp or gulp --version I get the following error. 

`C:\Users\Wizzo\Downloads\Compressed\project36\>gulp --version
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'object.defaults/immutable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Wizzo\AppData\Roaming\npm\node_modules\gulp\node_modules\fined\index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

I have gulp 4.0.0, node 10.15.0 and npm 6.6.0 installed.

I have checked immutable in the node_modules and it is there. I tried uninstalling node, and gulp and then re-install them again but the error persists.

**Comment by hkailahi** [comment]
+1 getting the same issue
