### ISSUE TITLE
library errors

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [gulpjs/gulp#2323]
Hi guys
I'm a beginner in JavaScript, I'm doing a bootstrap project, node.js, and sass is experiencing this error.
[laurianoelmiroduarte@lauriano src]$ gulp
[02:32:56] Using gulpfile ~/psscom/src/gulpfile.js
[02:32:56] Starting 'default'...
[02:32:56] Starting 'sass'...
[02:32:56] Starting '<anonymous>'...
[02:32:56] Finished '<anonymous>' after 17 ms
[02:32:56] Finished 'sass' after 18 ms
[02:32:56] Starting 'watch'...
[02:32:56] Starting '<anonymous>'...
[02:32:56] '<anonymous>' errored after 830 μs
[02:32:56] AssertionError [ERR_ASSERTION]: Task never defined: scss
    at getFunction (/home/laurianoelmiroduarte/psscom/node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at map (/home/laurianoelmiroduarte/psscom/node_modules/arr-map/index.js:20:14)
    at normalizeArgs (/home/laurianoelmiroduarte/psscom/node_modules/undertaker/lib/helpers/normalizeArgs.js:22:10)
    at Gulp.parallel (/home/laurianoelmiroduarte/psscom/node_modules/undertaker/lib/parallel.js:13:14)
    at /home/laurianoelmiroduarte/psscom/src/gulpfile.js:11:71
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/home/laurianoelmiroduarte/psscom/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[02:32:56] 'watch' errored after 1.9 ms
[02:32:56] 'default' errored after 22 ms

this is my gulp file 

var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', gulp.series( function() {
  return gulp.src(['node_modules/bootstrap/scss/*.scss', 'src/scss/* .scss'])
 .pipe(sass()) //converter o sass em css
 .pipe(gulp.dest('src/css'));
}));

gulp.task('watch', gulp.series( function() {
  gulp.watch(['node_modules/bootstrap/scss', 'src/scss/*.scss'], gulp.parallel(['scss']));
}));

gulp.task('default', gulp.series(['sass', 'watch']
));

thankfull all

**Comment by stevelacy** [comment]
If you check your string names you will see that you have written `scss` and not `sass`. 
It is clearly printed in the error from gulp.

**Comment by LaurianoElmiroDuarte** [comment]
@stevelacy the directorys are okay, i think to be a lib .. this code gulpfile.js
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', gulp.series( function() {
  return gulp.src(['node_modules/bootstrap/scss/*.scss', 'src/scss/* .scss'])
 .pipe(sass()) //converter o sass em css
 .pipe(gulp.dest('src/css'));
}));

gulp.task('watch', gulp.series( function() {
  gulp.watch(['node_modules/bootstrap/scss', 'src/scss/*.scss'], gulp.parallel(['scss']));
}));

gulp.task('default', gulp.series(['sass', 'watch']));

**Comment by phated** [comment]
@LaurianoElmiroDuarte perhaps you should read our new [Getting Started guide](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles) - it might help shed some light on your issues because using strings for tasks is very error prone.  But as the supportbot already said, this issue tracker is not for support issues so I'm going to lock this.
