### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by AngelDev727** [gulpjs/gulp#2523]
I am using gulp on my project.
By the way, as you can see on blow, I can run it.

Please help me to solve this.

rapunzel@Rapunzels-iMac blur-admin-master % gulp serve  

ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (/Users/rapunzel/Sites/angularjs/blur-admin-master/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/rapunzel/Sites/angularjs/blur-admin-master/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/rapunzel/Sites/angularjs/blur-admin-master/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)

**Comment by phated** [comment]
Support questions must go on our discussion board. I'll convert this for you.
