### ISSUE TITLE
gulp --require sucrase/register/ts

### ISSUE THREAD

**Issue by Valar103769** [gulpjs/gulp#2691]
i need help

i want use gulpfile.ts
the package.json with `"type": "module",`
```
{
  "name": "koa",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "server": "tsx watch ./src/index.ts",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "gulp": "gulp --require sucrase/register/ts"
  },
  "type": "module",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fingerprintjs/fingerprintjs": "^3.3.4",
    "@koa/cors": "^3.3.0",
    "@koa/router": "^12.0.0",
    "gradient-string": "^2.0.1",
    "gulp": "^4.0.2",
    "jquery": "^3.6.0",
    "koa": "^2.13.4",
    "koa-static": "^5.0.0",
    "prisma": "^4.2.1",
    "swipejs": "^2.3.1"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.26.1",
    "@prisma/client": "^4.2.1",
    "@types/gradient-string": "^1.1.2",
    "@types/gulp": "^4.0.9",
    "@types/gulp-postcss": "^8.0.2",
    "@types/jquery": "^3.5.14",
    "@types/koa": "^2.13.5",
    "@types/koa-static": "^4.0.2",
    "@types/koa__cors": "^3.3.0",
    "@types/koa__router": "^8.0.11",
    "@types/node": "^14.11.2",
    "autoprefixer": "^10.4.8",
    "chalk": "^5.0.1",
    "eslint": "^8.22.0",
    "gulp-postcss": "^9.0.1",
    "postcss": "^8.4.16",
    "postcss-px-to-viewport": "^1.1.1",
    "ts": "link:sucrase/register/ts",
    "tsx": "^3.8.2",
    "typescript": "^4.0.3"
  }
}

```
cause Error 
```
> gulp --require sucrase/register/ts

[15:40:04] Failed to load external module sucrase/register/ts
[15:40:04] Error: Cannot find module 'sucrase/register/ts' from '/Users/vayne/koa'
[15:40:04] Failed to load external module ts-node/register
[15:40:04] Error: Cannot find module 'ts-node/register' from '/Users/vayne/koa'
[15:40:04] Failed to load external module typescript-node/register
[15:40:04] Error: Cannot find module 'typescript-node/register' from '/Users/vayne/koa'
[15:40:04] Failed to load external module typescript-register
[15:40:04] Error: Cannot find module 'typescript-register' from '/Users/vayne/koa'
[15:40:04] Failed to load external module typescript-require
[15:40:04] Error: Cannot find module 'typescript-require' from '/Users/vayne/koa'
[15:40:04] Failed to load external module sucrase/register/ts
[15:40:04] Error: Cannot find module 'sucrase/register/ts' from '/Users/vayne/koa'
[15:40:04] Failed to load external module @babel/register
[15:40:04] Error: Cannot find module '@babel/register' from '/Users/vayne/koa'
/Users/vayne/koa/gulpfile.ts:1
import { dest, parallel, src } from 'gulp'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (/Users/vayne/koa/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/vayne/koa/node_modules/.pnpm/gulp-cli@2.3.0/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
 ELIFECYCLE  Command failed with exit code 1.
➜ koa (master) ✗ 
```

**Comment by Valar103769** [comment]
pnpm add sucrase instead of  pnpm add sucrase/register/ts
