### ISSUE TITLE
Sourcing files from a folder that doesn't exist using a glob pattern gives a cryptic error instead of nothing happening

### ISSUE THREAD

**Issue by datho7561** [gulpjs/gulp#2794]
### What were you expecting to happen?
Nothing (build succeeds with v4)

### What actually happened?
Cryptic error

### Please give us a sample of your gulpfile
Minimal reproducer: https://github.com/datho7561/gulp-glob-src-bug-reproducer

### Terminal output / screenshots

```sh
npm run build

> example-gulp@0.1.0 build
> gulp my-broken-task

[17:27:38] Using gulpfile ~/Documents/Projects/example-gulp/gulpfile.js
[17:27:38] Starting 'my-broken-task'...
[17:27:38] Finished 'my-broken-task' after 4.52 ms
node:events:492
      throw er; // Unhandled 'error' event
      ^

<ref *2> Error: ENOENT: no such file or directory, scandir '/home/davthomp/Documents/Projects/example-gulp/libs'
Emitted 'error' event on Domain instance at:
    at Transform.emit (node:domain:539:12)
    at ReadableState.afterDestroy (/home/davthomp/Documents/Projects/example-gulp/node_modules/streamx/index.js:493:19)
    at Transform._destroy (/home/davthomp/Documents/Projects/example-gulp/node_modules/streamx/index.js:629:5)
    at ReadableState.updateNonPrimary (/home/davthomp/Documents/Projects/example-gulp/node_modules/streamx/index.js:386:16)
    at ReadableState.update (/home/davthomp/Documents/Projects/example-gulp/node_modules/streamx/index.js:367:71)
    at ReadableState.updateReadNT (/home/davthomp/Documents/Projects/example-gulp/node_modules/streamx/index.js:536:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
```
Followed by a large JavaScript object output as JSON

### Please provide the following information:
* Fedora Linux 39
* 20.10.0
* 10.2.3
* 5.0.0

**Comment by phated** [comment]
Thanks for the report. I think I know where to fix this but it'll take some time.

We'll probably move this issue over to the glob-stream repository, as that's where the bug exists.
