### ISSUE TITLE
Can't install gulp (no pretty-hrtime)

### ISSUE THREAD

**Issue by speg** [gulpjs/gulp#329]
Hi guys, I am trying to install gulp for the first time and am getting this error:

``` bash
$ npm install -g gulp
npm http GET https://registry.npmjs.org/gulp
npm http 200 https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp/-/gulp-3.5.5.tgz
npm http 200 https://registry.npmjs.org/gulp/-/gulp-3.5.5.tgz
npm http GET https://registry.npmjs.org/gulp-util
npm http GET https://registry.npmjs.org/orchestrator
npm http GET https://registry.npmjs.org/pretty-hrtime
npm http GET https://registry.npmjs.org/vinyl-fs
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/archy
npm http GET https://registry.npmjs.org/deprecated
npm http GET https://registry.npmjs.org/liftoff
npm http GET https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/pretty-hrtime
npm ERR! Error: No compatible version found: pretty-hrtime@'^0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.2.0"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

Anyone run into this before?

**Comment by diyen1** [comment]
Thanks. Updating npm woked for me
