### ISSUE TITLE
gulp.watch: Error: watch ENOENT

### ISSUE THREAD

**Issue by caiotoon** [gulpjs/gulp#427]
I'm watching a folder for changes and deleting some folders and processing image files. I then intermittently get this error.

Sometimes, by restarting the watcher, the errors seems to disappear.

The last error on the stacktrace was `errnoException`.

As background, I've seem [this issue on Gaze](https://github.com/shama/gaze/issues/56). This issue has been fixed already, and I'm not sure if Gulp uses the latest version. I then searched for `vinyl-fs`, which Gulp uses for watching, and saw [this commit](https://github.com/wearefractal/vinyl-fs/commit/abd2fe4e1e32ef46d7544ce90fe941ece3a49a55), which means we're probably not using the latest version of Gaze for Gulp (not entirely sure, though).

Does it make any sense? Any idea on what could it be and how to investigate further?

```
Error: watch ENOENT
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at Gaze._watchDir (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:289:30)
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:358:10
    at iterate (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:52:5)
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:61:11
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:420:5
    at iterate (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:52:5)
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:61:11
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:420:5
    at iterate (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:52:5)
    at Object.forEachSeries (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\helper.js:66:3)
    at Gaze._initWatched (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:354:10)
    at Gaze._internalAdd (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:193:10)
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:400:16
    at Array.forEach (native)
    at code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\lib\gaze.js:396:12
    at ReaddirReq.Req.done (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:143:5)
    at ReaddirReq.done (code\source\node_modules\gulp\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:90:22)
    at Object.oncomplete (fs.js:107:15)
```

**Comment by Ndushi** [comment]
Still getting this issue in `gulp@3.9.0`

gulp crashed when I renamed a directory.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOENT
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/me/Projects/merithon/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
```

**Comment by Rolando-Barbella** [comment]
Getting the same error, I din't rename the directory, I'm using Linux

Node-v 0.10.33 which comes with gulp already

**Comment by andypearson** [comment]
+1 I'm seeing this too, when creating a directory in a directory that is being watched by `images/**/*.{jpg,gif,png,svg}`

**Comment by adambuczynski** [comment]
I'm getting this error with Gulp 4.0 when deleting a directory.

**Comment by fusepilot** [comment]
Also getting this with 4.0 when renaming a directory.

**Comment by adambuczynski** [comment]
@contra do you want to re-open this issue?

**Comment by contra** [comment]
Again, please see https://github.com/gulpjs/gulp/issues/651 this is a duplicate
