### ISSUE TITLE
'watch' errored after

### ISSUE THREAD

**Issue by ghost** [gulpjs/gulp#605]
Here's the code that does not cause errors -  

```
'use strict';

var gulp             = require('gulp');
var $                = require('gulp-load-plugins')();
var browserSync = require('browser-sync');
var mainBowerFiles = require('main-bower-files');

gulp.task('coffee', function(){
    return gulp.src('compile/src/*.coffee', {read:false})
    .pipe( $.browserify({
        debug:true,
        insertGlobals:false,
        transform:['coffeeify'],
        extension:['.coffee']
    }))
    .pipe($.rename('main.js'))
    .pipe(gulp.dest('./compiled/src'))
});

gulp.task('uglify', function(){
    gulp.src('compiled/src/main.js')
    .pipe($.uglify())
    .pipe($.rename('main.min.js'))
    .pipe(gulp.dest('src/lib/js/'))
});

gulp.task('server', function(){
    browserSync.init(
        {
            startPath:'/index.html',
            server:{
                baseDir:'./src/'
            }
        });
});

gulp.task('index', function(){
    browserSync.reload();
})

gulp.task('watch', function(){
    gulp.watch('./compile/src/*.coffee', ['coffee']);
    gulp.watch('./src/index.html', ['index']);
});


gulp.task('build', ['coffee', 'uglify', 'watch', 'server']);
```

And after I install - 

```
bower install --save angular
```

you receive an error message -  

```
[23:24:29] Using gulpfile ~/test/gulpfile.js
[23:24:29] Starting 'default'...
[23:24:29] Starting 'coffee'...
[23:24:30] Starting 'uglify'...
[23:24:30] Finished 'uglify' after 253 ms
[23:24:30] Starting 'watch'...
[23:24:30] 'watch' errored after 26 ms
[23:24:30] Error: watch ENOSPC
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at Gaze._watchDir (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/acopalipsis/test/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
[23:24:30] Finished 'default' after 1.32 s
[23:24:30] Finished 'coffee' after 1.81 s
```

Can't understand why?

**Comment by aman199002** [comment]
@contra:  +1. Stackoverflow referance worked.

**Comment by RodolfoSilva** [comment]
+1. Stackoverflow referance worked.
