### ISSUE TITLE
Unable to require anything in CoffeeScript or LiveScript

### ISSUE THREAD

**Issue by dead-claudia** [gulpjs/gulp#638]
The require functionality seems completely broken as far as I can tell with at least these two languages, and possibly more. Here's the error screens I'm getting:

CoffeeScript

```
[23:20:01] Failed to load external module coffee-script/register

/home/{user}/dev-projects/js/sandbox/gulpfile.coffee:1
function (exports, require, module, __filename, __dirname) { fs = require 'fs'
                                                                          ^^^^
SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:108:3)
    at Liftoff.launch (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:140:6)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:59:5)
    at Module._compile (module.js:456:26)
```

LiveScript

```
(function (exports, require, module, __filename, __dirname) { require! {
                                                                     ^
SyntaxError: Unexpected token !
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:108:3)
    at Liftoff.launch (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:140:6)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:59:5)
    at Module._compile (module.js:456:26)
```

JS does not have this issue, but it seems like a bug that both CoffeeScript and LiveScript should fail in exactly the same spot (namely the beginning require phase).

**Comment by larrybotha** [comment]
For anyone coming across an issue with the

```shell
Failed to load external module coffee-script/register
```
issue, check if you indeed have coffee-script installed:

```shell
$ npm ls coffee-script
your-app@1.0.0
└── coffee-script@1.9.0
```
If you have it installed, delete the `node_modules` folder, and rerun your install:

```shell
$ npm install
```

**Comment by tkellen** [comment]
Working fine on this end: https://github.com/tkellen/gulp-with-coffee-script

**Comment by larrybotha** [comment]
ye, it's something weird with the order you install coffee-script / run gulpfile.coffee. I just had this issue with a new repo that I didn't have yesterday on another repo.

Just a note should someone not know how to quickly resolve it.

**Comment by artelse** [comment]
Sorry about reopening here, but I got the same error: `Requiring external module coffee-script/register`. I tried above suggestions, but no dice. Coffee-script is local in `node_modules` and also globally installed and removed and reinstalled the `node_modules`. gulp@3.9.1 and node@6.6.0.
