### ISSUE TITLE
is gulpfile.coffee supported out of the box with gulp >= 3.7.0?

### ISSUE THREAD

**Issue by iki** [gulpjs/gulp#717]
After reading #103, #123, and #452, I got impression that `gulpfile.coffee` is supported out of the box with gulp >= 3.7.0. Is that true?

For me, it fails on win8.0 x64 with node 0.10.32 and local+global gulp 3.8.8.

Steps to reproduce:
1. `mkdir test && cd test`
2. `echo require 'gulp' > gulpfile.coffee` on windows,
  or `echo "require 'gulp'" > gulpfile.coffee` on linux/mac
3. `npm install -g gulp`
4. `npm install gulp coffee-script`
5. `gulp`

Expected result is gulp complaining about missing default task.
Actual result:

```
D:\test\gulpfile.coffee:1
tion (exports, require, module, __filename, __dirname) { gulp = require 'gulp'
                                                                        ^^^^^^
SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (C:\Users\x\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:108:3)
    at Liftoff.launch (C:\Users\x\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:143:6)
    at Object.<anonymous> (C:\Users\x\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:59:5)
    at Module._compile (module.js:456:26)
```

Both the old workarounds do work:
1. either `gulp --require coffee-script/register`
2. or `echo require('coffee-script/register'); require('./gulpfile.coffee'); > gulpfile.js` before `gulp`

**Comment by brunocoelho** [comment]
I had this problem today using `gulp@3.9.1` and I had to install `coffee-script` locally in order to make it work.

**Comment by tkellen** [comment]
This is expected. Gulp does not require coffee-script to function properly. If we bundle coffee-script we have to release a new version of Gulp when coffee-script changes. Installing locally is the best/recommended practice.
