### ISSUE TITLE
v8flags node error

### ISSUE THREAD

**Issue by sashasochka** [gulpjs/gulp#774]
Hi, with gulp 3.8.9 and 3.8.10 I get the following error:

```
[INFO] > gulp build
[INFO] 
[INFO] 
[INFO] Error: Cannot find module '/home/oleksandr/Projects/wdc/src/main/webapp/node_modules/gulp/node_modules/v8flags/3.14.5.9.flags.json'
[INFO]     at Function.Module._resolveFilename (module.js:338:15)
[INFO]     at Function.Module._load (module.js:280:25)
[INFO]     at Module.require (module.js:364:17)
[INFO]     at require (module.js:380:17)
[INFO]     at Object.<anonymous> (/home/oleksandr/Projects/wdc/src/main/webapp/node_modules/gulp/bin/gulp.js:25:22)
[INFO]     at Module._compile (module.js:456:26)
[INFO]     at Object.Module._extensions..js (module.js:474:10)
[INFO]     at Module.load (module.js:356:32)
[INFO]     at Function.Module._load (module.js:312:12)
[INFO]     at Function.Module.runMain (module.js:497:10)
[INFO] 
```

Gulp 3.8.8 works fine. I'm on Linux Mint 13.10

**Comment by chokri** [comment]
Hi, I ran sudo npm install -g gulp and I found this:
```Shell
npm WARN install:duplexer2 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2' -> '/usr/local/lib/node_modules/gulp/node_modules/duplexer2'
- lru-cache@2.7.0 node_modules/gulp/node_modules/globule/node_modules/minimatch/node_modules/lru-cache
- sigmund@1.0.1 node_modules/gulp/node_modules/globule/node_modules/minimatch/node_modules/sigmund
duplexer2@0.0.2 node_modules/gulp/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2 -> node_modules/gulp/node_modules/duplexer2
- /usr/local/lib/node_modules/gulp/node_modules/mkdirp node_modules/gulp/node_modules/mkdirp
- /usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/multipipe node_modules/gulp/node_modules/gulp-util/node_modules/multipipe
- /usr/local/lib/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream
/usr/local/lib
└── (empty)

npm ERR! code 1
```

**Comment by callumacrae** [comment]
@chokri uninstall and reinstall gulp
