### ISSUE TITLE
Gulp 4 task alias

### ISSUE THREAD

**Issue by ilanbiala** [gulpjs/gulp#844]
How can I have a task `nodemon` get aliased to also be callable through `gulp dev`? Does it make sense to have to do `gulp.task('dev', gulp.series('nodemon'));` instead of `gulp.task('dev', 'nodemon');`?

When I do the first code snippet, I get an error:

```
AssertionError: Task function must be specified
    at Gulp.set (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp/node_modules/undertaker/lib/set.js:14:3)
    at Gulp.task (/Users/Eytan/Desktop/hths-lunch/node_modules/gulp/node_modules/undertaker/lib/task.js:14:8)
    at Object.<anonymous> (/Users/Eytan/Desktop/hths-lunch/gulpfile.js:168:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:136:3)
```

**Comment by Zorgatone** [comment]
@ilanbiala looking at the log seems to me more likely to be an error with the `undertaker` package, did the named function solve your problem?
