### ISSUE TITLE
Cannot install gulp CLI

### ISSUE THREAD

**Issue by djmadeira** [gulpjs/gulp#852]
I can install/uninstall other global tools just fine, for example: `sudo npm un -g clean-css` and `sudo npm install -g clean-css` both run fine for me. But when I run `sudo npm install -g gulp`, I get the following error:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:838
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! v8flags@1.0.8 install: `node fetch.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the v8flags@1.0.8 install script 'node fetch.js'.
npm ERR! This is most likely a problem with the v8flags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fetch.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8flags
npm ERR! There is likely additional logging output above.
```

[Here's my full npm-debug.log](http://sitesahoy.com/uploads/npm-debug-14-01-04.log).

**Comment by contra** [comment]
your npm install is messed up, search for the issue there - this has nothing to do with gulp
