### ISSUE TITLE
Cryptic error messages - debugging tasks is hard

### ISSUE THREAD

**Issue by mik01aj** [gulpjs/gulp#881]
Hi, I just created a new project using `yo react-gulp-browserify`. I run `gulp watch` and get the following output:

````
[12:17:28] Using gulpfile ~/code/react-frontend/gulpfile.js
[12:17:28] Starting 'html'...
[12:17:28] Starting 'scripts'...
[12:17:28] Starting 'bower'...
[12:17:28] Finished 'bower' after 1.34 ms
[12:17:28] Starting 'serve'...
[12:17:28] Webserver started at http://localhost:9000
[12:17:28] Finished 'serve' after 231 ms
[12:17:28] all files 1.87 kB
[12:17:28] Finished 'html' after 501 ms
[12:17:30] Finished 'scripts' after 2.04 s
[12:17:30] Starting 'bundle'...

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)
    at Transform.onerror (/Users/mik01aj/code/react-frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:95:17)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Users/mik01aj/code/react-frontend/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)
```

My point is, the error message should contain some basic information like:

* where is the `events.js` file specified in the stacktrace?
* what line in my gulpfile caused the problem?
* what plugin caused the problem?
* what task caused the problem? (was it `bundle`? Can I be sure?)
* (ideally) how can I fix it?

What's even more interesting, I searched all the files in my `node_modules` for the line and here's what I found: 

```
node_modules/browserify/node_modules/events/events.js
61:      throw TypeError('Uncaught, unspecified "error" event.');

node_modules/gulp-jshint/node_modules/jshint/dist/jshint-rhino.js
467:      throw TypeError('Uncaught, unspecified "error" event.');

node_modules/gulp-jshint/node_modules/jshint/dist/jshint.js
465:      throw TypeError('Uncaught, unspecified "error" event.');

node_modules/watchify/node_modules/browserify/node_modules/events/events.js
61:      throw TypeError('Uncaught, unspecified "error" event.');
```

None of them is `events.js:74`, specified in the stacktrace.

All this makes gulp tasks extremely hard to debug.

**Comment by mik01aj** [comment]
This might be related to https://github.com/gulpjs/gulp/issues/359.

**Comment by heikki** [comment]
https://github.com/joyent/node/blob/v0.10.36/lib/events.js#L74

Similar issue from the generator you're using:
https://github.com/randylien/generator-react-gulp-browserify/issues/15

**Comment by mik01aj** [comment]
@heikki ,  while this might solve my problem with `react-gulp-browserify`, my point about error messages remains valid. But thanks for the help, anyway :)

**Comment by heikki** [comment]
Yes, I contributed what I could on short notice. :smile:

**Comment by phated** [comment]
This is a normal async stack trace in node.  If you are having problems, I would suggest using a module like https://www.npmjs.com/package/stackup at the top of your gulpfile to get long stack traces.
