### ISSUE TITLE
Gulp error on Node 0.12.0

### ISSUE THREAD

**Issue by SAnDAnGE** [gulpjs/gulp#893]
```winbatch
C:\Zend\Apache2\htdocs\u3c>gulp -T
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Emanuel\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\3.28.73.flags.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Emanuel\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by jameswomack** [comment]
@SAnDAnGE This will be fixed if you uninstall and reinstall Gulp with the new version of Node.

**Comment by AbdullahDiaa** [comment]
`npm uninstall -g gulp`
`npm install -g gulp`
Should fix your problem.

**Comment by SAnDAnGE** [comment]
Thank you, this solves the problem.

**Comment by Egidius** [comment]
Thanks AbdullahDiaa!

**Comment by phated** [comment]
This is fixed in gulp 3.8.11, no need to reinstall anymore, as flags are fetched upon startup if we don't already have them.

**Comment by LitterPapmasa** [comment]
Thanks. +1

**Comment by firetix** [comment]
Thanks!!+1

**Comment by phated** [comment]
Locking as this is fixed and +1s are just noise.
