### ISSUE TITLE
Can't use gulp-sass anymore because it keeps installing 2.0 beta

### ISSUE THREAD

**Issue by kylescousin** [gulpjs/gulp#897]
npm install gulp-sass@1.3.2

Gives: node-sass@2.0.0-beta install
node-sass@2.0.0-beta postinstall

Then when running gulp it says:
Module._extensions[extension](this, filename);
                               ^
Error: no errorc:\Users\...\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node
 at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\...\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Any idea how to fix this?

**Comment by heikki** [comment]
Wrong repo? Try here: https://github.com/dlmanning/gulp-sass
