### ISSUE TITLE
Doesn't seem to work with Node v0.12.0

### ISSUE THREAD

**Issue by misteroh** [gulpjs/gulp#898]
Running gulp with Node v0.12 yields this error:

module.js:347
        ' for module ' + JSON.stringify(this.id));
                       ^
Error: The specified procedure could not be found.
c:\Users\xxx\workspace\xxx\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\Artur\workspace\xxx\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by heikki** [comment]
Look at the stacktrace. Here's links to correct places:

- https://github.com/dlmanning/gulp-sass/issues/189#issuecomment-73430602
- https://github.com/sass/node-sass/issues/653#issuecomment-73381370

**Comment by misteroh** [comment]
My apologies. Thank you
