### ISSUE TITLE
Gulp Error: listen EACCES

### ISSUE THREAD

**Issue by shruts2907** [gulpjs/gulp#908]
I am trying to run gulp command on my git bash (Windows 7 OS)  with administrative privilege, still I am getting following error, the browser should fire at 8080

Shruts@SHRUTS-VAIO /c/xampp/htdocs/ng/Angular_JS/angulardata
(master)
$ gulp
[00:43:43] Using gulpfile c:\xampp\htdocs\ng\Angular_JS\angul
ardata\gulpfile.js
[00:43:43] Starting 'watch'...
[00:43:43] Finished 'watch' after 29 ms
[00:43:43] Starting 'html'...
[00:43:43] Finished 'html' after 4.58 ms
[00:43:43] Starting 'js'...
[00:43:43] Finished 'js' after 1.13 ms
[00:43:43] Starting 'css'...
[00:43:43] Finished 'css' after 621 µs
[00:43:43] Starting 'webserver'...
[00:43:43] Webserver started at http://localhost:8000
[00:43:43] Finished 'webserver' after 6.15 ms
[00:43:43] Starting 'default'...
[00:43:43] Finished 'default' after 5.35 µs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by heikki** [comment]
http://stackoverflow.com/questions/12127293/writing-a-node-application-and-encountering-an-error-when-running-node-server-j

Support questions http://stackoverflow.com/questions/tagged/gulp
