### ISSUE TITLE
have nice error message on circular dependency

### ISSUE THREAD

**Issue by david-gang** [gulpjs/gulp#914]
Having this nice javascript:

```javascript
var gulp = require('gulp');

gulp.task('a', function() {
    console.log("hi");
});

gulp.task('b',['b'], function() {
    console.log("hi");
});
```

When running gulp b the output is:
>J:\webstorm_workspace\primo-explore>gulp --gulpfile x.js b
>[10:19:32] Using gulpfile J:\webstorm_workspace\primo-explore\x.js

There should be a nice error message:
cannot run b because of circular dependency b->b

**Comment by contra** [comment]
Not going to get added since work on the 3.0 branch is finished, we are working on 4.0 now. You should switch to that branch. We replaced the whole task system.

@phated what does this do in 4.0?

**Comment by heikki** [comment]
```js
var gulp = require('gulp');

gulp.task('b', gulp.parallel('b', function() {
    console.log('hi');
}));
```

```sh
∴ gulp b

AssertionError: Task never defined: b
    at getFunction (/Users/heikki/Desktop/foo/node_modules/gulp/node_modules/undertaker/lib/helpers/normalizeArgs.js:14:5)
    at Function.map (/Users/heikki/Desktop/foo/node_modules/gulp/node_modules/undertaker/node_modules/lodash/dist/lodash.js:3508:27)
    at normalizeArgs (/Users/heikki/Desktop/foo/node_modules/gulp/node_modules/undertaker/lib/helpers/normalizeArgs.js:18:12)
    at Gulp.parallel (/Users/heikki/Desktop/foo/node_modules/gulp/node_modules/undertaker/lib/parallel.js:12:14)
    at Object.<anonymous> (/Users/heikki/Desktop/foo/gulpfile.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by contra** [comment]
@david-gang Good enough?

**Comment by david-gang** [comment]
@contra

Yes :+1: 

This snippet is enough to trace the issue:

>at Gulp.parallel (/Users/heikki/Desktop/foo/node_modules/gulp/node_modules/undertaker/lib/parallel.js:12:14)
>at Object.<anonymous> (/Users/heikki/Desktop/foo/gulpfile.js:3:21)

It would be nicer to have the line

>at gulp.task (/Users/heikki/Desktop/foo/gulpfile.js:3:1)

but i am not sure that it is easy to achieve this and for the people who won't understand this, they will google and get hopefully to this page :-)

From my viewpoint it can be closed.

**Comment by xtianus79** [comment]
I am getting the error @heikki and I don't see anything from this page that explains what the error is or how to fix it. perhaps I am missing something.

**Comment by xtianus79** [comment]
I found this and the fix at the bottom might have been the fix... http://blog.reactandbethankful.com/posts/2015/05/01/how-to-install-gulp-4/
