### ISSUE TITLE
Getting error running gulp

### ISSUE THREAD

**Issue by ricardomasao** [gulpjs/gulp#936]
I upgraded to Mac OSX Yosemite and I can no longer run gulp.

npm -v => 2.5.1
node -v => v0.11.16

Error below:

```
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/ImagePrototypeInit'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/ricardoshigeoka/Jobs/Brastemp/Menu/node_modules/css-sprite/node_modules/lwip/index.js:1:63)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/ricardoshigeoka/Jobs/Brastemp/Menu/node_modules/css-sprite/lib/css-sprite.js:12:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/ricardoshigeoka/Jobs/Brastemp/Menu/node_modules/css-sprite/index.js:3:14)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/ricardoshigeoka/Jobs/Brastemp/Menu/gulpfile.js:13:14)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:62:18)
  at Liftoff.launch (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:144:6)
  at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:25:5)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by heikki** [comment]
Try reinstalling node modules / node.

**Comment by contra** [comment]
rebuild your dependencies

**Comment by ricardomasao** [comment]
Thanks!
