### ISSUE TITLE
module.js:111 throw e; ^ SyntaxError: Error parsing e:directory\node_modules\gulp-jade\pa ckage.json Unexpected token

### ISSUE THREAD

**Issue by Robert-Janagap** [gulpjs/gulp#938]
I'm trying to run my gulp packages.
$ gulp
module.js:111
    throw e;
          ^
SyntaxError: Error parsing e:\Projects\PersonalWebsite\node_modules\gulp-jade\pa
ckage.json: Unexpected token <
    at Object.parse (native)
    at readPackage (module.js:107:52)
    at tryPackage (module.js:117:13)
    at Function.Module._findPath (module.js:183:18)
    at Function.Module._resolveFilename (module.js:334:25)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (e:\Projects\PersonalWebsite\gulpfile.js:8:15)
    at Module._compile (module.js:460:26)

**Comment by heikki** [comment]
Support questions http://stackoverflow.com/questions/tagged/gulp
