### ISSUE TITLE
When running 'gulp'

### ISSUE THREAD

**Issue by leetoufong** [gulpjs/gulp#953]
When I run 'gulp', I get:
```
SM-C02MN0Y3FD58:webapp tou.lee$ gulp
[17:36:16] Using gulpfile /private/var/reposwebapp/gulpfile.js
[17:36:16] Starting 'clean'...
[17:36:16] Finished 'clean' after 20 ms
[17:36:16] Starting 'default'...
[17:36:16] Starting 'jshint'...
[17:36:16] Starting 'styles'...
[17:36:16] Starting 'images'...
[17:36:17] Starting 'fonts'...
[17:36:17] Starting 'extras'...
[17:36:17] Finished 'default' after 1.54 s
[17:36:17] Finished 'jshint' after 1.6 s
[17:36:18] Finished 'styles' after 1.59 s
[17:36:18] Starting 'html'...
[17:36:18] Finished 'extras' after 751 ms
[17:36:18] Finished 'images' after 1.79 s

events.js:85
      throw er; // Unhandled 'error' event
            ^
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at compact (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/helpers.js:34:16)
    at Helpers.text (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/helpers.js:223:15)
    at enter (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:120:45)
    at reduce (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:106:33)
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:272:13
    at iterate (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:149:13)
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:160:25
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:274:17
    at close (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:137:7)
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:277:13
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:157:25
    at /private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/node_modules/async/lib/async.js:274:17
    at close (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:137:7)
    at enter (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:121:37)
    at reduce (/private/var/repos/webapp/node_modules/gulp-minify-html/node_modules/minimize/lib/minimize.js:106:33)
```

When commenting out this line `.pipe($.if('*.html', $.minifyHtml({conditionals: true, loose: true})))` in my gulp file, it seems to compile okay but my html doesn't get minimized.

Any help would do please.

**Comment by callumacrae** [comment]
That looks like a problem with the gulp-minify-html plugin or how you're using it: I'd suggest opening an issue over there.

https://github.com/jonathanepollack/gulp-minify-html

cc/ @jonathanepollack

**Comment by phated** [comment]
I believe that module needs to be blacklisted, as https://github.com/jonschlinkert/gulp-htmlmin is the suggested html minifier plugin.

**Comment by jonathanepollack** [comment]
I didn't realize [html-min](https://github.com/jonschlinkert/gulp-htmlmin) was the blessed plugin--where is the suggested list, again? Also, should I, then, deprecate my plugin?

**Comment by callumacrae** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

There should only be one gulp plugin for each thing: in this case, there was already a plugin for HTML minification. If you don't like something about it, everything is on GitHub, contribute to the existing one!

(This is a guess: I am not @phated or gulp team, but it seems logical).

**Comment by jonathanepollack** [comment]
I agree with the guidelines, and have no issues with them--I just can't find the blacklist (and [Recommended Modules](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/recommended-modules.md) doesn't seem to have an HTML-minifier preference).

I also know that there is no way for me to say the following without sounding defensive, so please believe me when I say: I am not married to my plugin, and if the community wants to bless something else, I support that decision.

1. My plugin was created first (July of 2013 vs December of 2013)
2. My plugin has a fair bit more weekly downloads (11,605 vs 2,415)

**Comment by sindresorhus** [comment]
https://github.com/gulpjs/plugins/blob/master/src/blackList.json

**Comment by jonathanepollack** [comment]
^ Duh.

Well it seems from the blacklist, that `gulp-htmlmin` is the way to go. So the question stands: how should I proceed?

**Comment by jonathanepollack** [comment]
No ideas? @phated @sindresorhus @shinnn
