### ISSUE TITLE
Not able to see any plugin on http://gulpjs.com/plugins/ page.

### ISSUE THREAD

**Issue by eswarreddy43** [gulpjs/gulp#965]
Hi Team,

I am not finding any plugin in the http://gulpjs.com/plugins/ page. 

Please check.

**Comment by eswarreddy43** [comment]
It took so much time to load like 15 or 20 min.

**Comment by contra** [comment]
I probably need to resize the VM I'm traveling though

**Comment by eswarreddy43** [comment]
Hi @contra ,

Thanks for your quick response.

I got this error in console. Please check if it may useful..

```
vendor.js:34 GET http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,…odified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20 net::ERR_EMPTY_RESPONSE
vendor.js:34 TypeError: Cannot read property 'hits' of undefined
    at formatData (http://gulpjs.com/plugins/js/app.js:1:498)
    at http://gulpjs.com/plugins/js/vendor.js:34:875
    at Array.forEach (native)
    at forEach (http://gulpjs.com/plugins/js/vendor.js:32:1396)
    at transformData (http://gulpjs.com/plugins/js/vendor.js:34:893)
    at transformResponse (http://gulpjs.com/plugins/js/vendor.js:34:2052)
    at wrappedErrback (http://gulpjs.com/plugins/js/vendor.js:34:30662)
    at http://gulpjs.com/plugins/js/vendor.js:35:91
    at Scope.$eval (http://gulpjs.com/plugins/js/vendor.js:35:8463)
    at Scope.$digest (http://gulpjs.com/plugins/js/vendor.js:35:6316)
8content_script.js:1 Uncaught TypeError: Cannot set property 'maxLeft' of undefined
```

**Comment by travm** [comment]
Anyone still seeing this? I cannot replicate on my end so I think it may have resolved itself.

**Comment by callumacrae** [comment]
It's on and off

**Comment by contra** [comment]
I upgraded the VM it should be fine though, but running an elasticsearch with all of npm in it is costing 50/mo

**Comment by phated** [comment]
Thanks @contra - closing this now.
